### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by logg-sar** [ngoduykhanh/wireguard-ui#102]
Hi there

I'm using this dockerfile: https://github.com/ngoduykhanh/wireguard-ui/blob/master/Dockerfile on CentOS 7.9
However
**docker build -t wireguard-ui .**
gives me

_Sending build context to Docker daemon  4.608kB
Step 1/22 : FROM golang:1.16.7-alpine3.14 as builder
 ---> 6940794170d1
Step 2/22 : LABEL maintainer="Khanh Ngo <k@ndk.name"
 ---> Using cache
 ---> ef77de2a09d6
Step 3/22 : ARG BUILD_DEPENDENCIES="npm     yarn"
 ---> Using cache
 ---> 79584d7eab75
Step 4/22 : RUN apk add --update --no-cache ${BUILD_DEPENDENCIES}
 ---> Using cache
 ---> 2bd0405b91c8
Step 5/22 : WORKDIR /build
 ---> Using cache
 ---> f65cc6df69e0
Step 6/22 : COPY . /build
 ---> Using cache
 ---> ca1b9ba8ee59
Step 7/22 : RUN yarn install --pure-lockfile --production &&     yarn cache clean
 ---> Using cache
 ---> 0685a448b660
Step 8/22 : RUN mkdir -p assets/dist/js assets/dist/css &&     cp /build/node_modules/admin-lte/dist/js/adminlte.min.js     assets/dist/js/adminlte.min.js &&     cp /build/node_modules/admin-lte/dist/css/adminlte.min.css     assets/dist/css/adminlte.min.css
 ---> Running in b4e291018ca8
cp: can't stat '/build/node_modules/admin-lte/dist/js/adminlte.min.js': No such file or directory
The command '/bin/sh -c mkdir -p assets/dist/js assets/dist/css &&     cp /build/node_modules/admin-lte/dist/js/adminlte.min.js     assets/dist/js/adminlte.min.js &&     cp /build/node_modules/admin-lte/dist/css/adminlte.min.css     assets/dist/css/adminlte.min.css' returned a non-zero code: 1_

**Comment by Cr0w1ey** [comment]
I get the same thing on a Pi - I guess /build/node_modules/admin-lte/dist/js/adminlte.min.js isn't where the build script's expecting it to be? I'm pretty new to this.

**Comment by N4v41** [comment]
the aarch of the system where u are building is amd64 ? if not you need to change the line 47 of the docker compose file for the system aarch.
