### ISSUE TITLE
Status page: "socket: invalid argument"

### ISSUE THREAD

**Issue by tituspijean** [ngoduykhanh/wireguard-ui#103]
Hello,

I am facing this issue with the latest 0.3.2 version (binary, not docker) on Status page: `socket: invalid argument`.

![image](https://user-images.githubusercontent.com/8769166/132823171-e4d8c688-8fad-4da5-822b-190184b54735.png)

Unfortunately I cannot find how to debug it further. Let me know if you need more information.

**Comment by tituspijean** [comment]
FYI I investigated a little bit more. I had too restrictive systemd safety flags on the service running the app, but I also discovered that this feature requires the app to be run as `root`. Is there any way around that?

**Comment by ubergesundheit** [comment]
@tituspijean can you share your current systemd service file? I think something more restrictive wouldn't hurt. Thanks in advance

**Comment by ubergesundheit** [comment]
I think this works, but I am no systemd guru

```
# systemd --version
systemd 247 (247.3-6)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
# cat /etc/issue
Debian GNU/Linux 11 \n \l
```

```
[Unit]
Description=wireguard-ui daemon
After=network.target
Wants=network-online.target

[Service]
Restart=always
RestartSec=3
Type=simple
WorkingDirectory=/etc/wireguard-ui
ReadWritePaths=/etc/wireguard-ui /etc/wireguard
ExecStart=/usr/local/bin/wireguard-ui
Environment="SESSION_SECRET=somethingsecret"
Environment="BIND_ADDRESS=127.0.0.1:5000"

PrivateTmp=true
PrivateDevices=true

CapabilityBoundingSet=CAP_NET_ADMIN
AmbientCapabilities=

ProtectSystem=strict
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
ProtectClock=true
ProtectHostname=true

ProtectHome=tmpfs
ProtectKernelLogs=true

ProtectProc=invisible
ProcSubset=pid

PrivateNetwork=false
IPAddressAllow=any

SystemCallArchitectures=native
SystemCallFilter=@system-service
SystemCallFilter=~@privileged @resources @obsolete

RestrictSUIDSGID=true
RemoveIPC=true
NoNewPrivileges=true
RestrictRealtime=true
RestrictNamespaces=true
LockPersonality=true
MemoryDenyWriteExecute=false

[Install]
WantedBy=multi-user.target
```

**Comment by tituspijean** [comment]
Here is the current systemd file: https://github.com/YunoHost-Apps/wireguard_ynh/blob/1929f4bba09c03c78c439d8eddbc6dbd13c93637/conf/wireguard_ui.service

I will compare it with your suggested file. I guess we are stuck with it running as `root`, though.

**Comment by Moulick** [comment]
I have the same issue while running via docker-compose.
