### ISSUE TITLE
Regular SMTP Support

### ISSUE THREAD

**Issue by subdavis** [ngoduykhanh/wireguard-ui#106]
While sendgrid support is great, it's a bit unusual to be the only outgoing email option.  SMTP credentials would allow users to support almost any outgoing mail configuration they already had instead of having to sign up for sendgrid.

**Comment by antedebaas** [comment]
+1

**Comment by snax44** [comment]
+1

**Comment by subdavis** [comment]
Use the 👍 if you don't have anything useful to add. Do not comment +1 on GitHub.

The maintainers can sort issues by upvote count to see what requests are popular, and you don't send everyone a notification.

**Comment by Gum97** [comment]
+1

**Comment by HaleyACS** [comment]
I definitely agree with that. Regular SMTP transport would be great. As I host my own mails etc., I see no reason to actually use any type of external mail-service to send out mails.
So +1

**Comment by exilewolf** [comment]
Also run my own SMTP and would like to see this feature if you get so inclined :)

**Comment by ngoduykhanh** [comment]
Feature added in https://github.com/ngoduykhanh/wireguard-ui/pull/146
