### ISSUE TITLE
wrong time format

### ISSUE THREAD

**Issue by KleSecGmbH** [ngoduykhanh/wireguard-ui#115]
I´m experiencing some issues with the time format. Maybe this needs to be changed in the docker container, but i.d.k.

![image](https://user-images.githubusercontent.com/91429214/141104245-51c834d2-60bb-4647-940f-e92a00faaf4c.png)

Is there something i can do about that?

**Comment by ngoduykhanh** [comment]
Hello, what is the expected format you are looking for?

**Comment by KleSecGmbH** [comment]
It would be great to have it like you provided in your screenshots.
![image](https://user-images.githubusercontent.com/91429214/141286197-371384a9-ee7f-4803-8abf-6aa58129a62e.png)
I guess I could fix it myself by changing

routes.go line 178
`client.CreatedAt = time.Now().UTC()`
and line 277
`client.UpdatedAt = time.Now().UTC()`

to
`client.CreatedAt = time.Now().UTC().Format("01-02-2006 15:04:05")`
and
`client.UpdatedAt = time.Now().UTC().Format("01-02-2006 15:04:05")`

But i have no experience in Golang whatsoever, if so i could make a PR

**Comment by ngoduykhanh** [comment]
Fixed in the linked PR.
