### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by Larbi75** [ngoduykhanh/wireguard-ui#125]
Hi

Will it be possible to add
- wireguard-ui version from command line
- dynamic YEAR in footer page (<strong>Copyright &copy; 2020 <a href="https://github.com/ngoduykhanh/wireguard-ui">Wireguard UI</a>.</strong> All rights), it should be 2021 instead 2020

Thanks

**Comment by ngoduykhanh** [comment]
1. No, the version will be injected during the build time of the software and cannot be changed.
2. I merged the linked PR to fix the YEAR issue.
