### ISSUE TITLE
Sending conf by email not working AND client status page showing blank

### ISSUE THREAD

**Issue by astronyu** [ngoduykhanh/wireguard-ui#127]
For some reason I could not get the email feature to work. When clicked it says successfully sent the email but I do not receive the configuration file, no where to be found even in spam.

I have the key etc setup as per instruction.

As for the status page, it is showing blank. Can someone help?

**Comment by ngoduykhanh** [comment]
Are you running `wireguard-ui` using binary or docker? If you are using docker, please make sure you have these config enabled
```
    cap_add:
      - NET_ADMIN
    network_mode: host
```

Also, connect your 1st client to wg server to let the UI display them.

Regarding the email, were there any logs/events recorded in your Sendgird account?
