### ISSUE TITLE
MTU setting is missing in client config

### ISSUE THREAD

**Issue by bh** [ngoduykhanh/wireguard-ui#136]
I set the MTU to 1400 in "Global Settings". The MTU paramter in the client configs is missing. Need to set them manually.

This was generated:
```[root@helium ~]# cat /etc/wireguard/wg0.conf 
[Interface]
Address = 10.10.10.2/24
PrivateKey = XXX
DNS = 1.1.1.1

[Peer]
PublicKey = XXX
PresharedKey = XXX
Endpoint = XXX:51820
PersistentKeepalive = 30
```

This would I expected if the global MTU setting value is not the default value:
```[root@helium ~]# cat /etc/wireguard/wg0.conf 
[Interface]
Address = 10.10.10.2/24
PrivateKey = XXX
DNS = 1.1.1.1
MTU = 1400

[Peer]
PublicKey = XXX
PresharedKey = XXX
Endpoint = XXX:51820
PersistentKeepalive = 30
```

P.S.: The server config always include the MTU paramter.

**Comment by bh** [comment]
Nice way to resolving issues. Good work!

**Comment by g3n35i5** [comment]
@bh The Stale Bot is a feature of github. No reason to blame the developer of an **OpenSource** project.


Apart from that, I would also love this feature!

**Comment by cheindel** [comment]
Hi @ngoduykhanh . Are there any intentions to fix this? Is there a reason it is not included in the file being generated?

**Comment by sudanking** [comment]
any updates regarding this?
