### ISSUE TITLE
Possible Security Issue

### ISSUE THREAD

**Issue by alexanderxc** [ngoduykhanh/wireguard-ui#143]
Installed wireguard-ui via docker-compose. Runs well, but the files that are created on the disk folder that is mounted onto the container are saved with the following permissions: 

`-rw-r--r--    1 root     root           505 Jan 19 22:25 c7k8......`

Personally this represent a considerable security risk (especially if other users or services are running on the same machine), as everyone is able to read the continue that is stored inside the file. Permission should be set to `600` and possibly this info should be store inside a db. 

Cheers.

**Comment by Zerogiven** [comment]
https://docs.docker.com/engine/security/rootless/#:~:text=Rootless%20mode%20allows%20running%20the,as%20the%20prerequisites%20are%20met.
