### ISSUE TITLE
Error starting UI if no public ip is available

### ISSUE THREAD

**Issue by Zerogiven** [ngoduykhanh/wireguard-ui#145]
Hi,

Got a problem installing wireguard-ui on my raspberry4(aarch64). At the JSON DB init you call util.GetPublicIP which ends for me with a "panic: no IP could be found". But for example if i call ```curl http://checkip.amazonaws.com/``` i will get my public ip. However if i just set my public ip hard coded as string the UI works like a charm. So for now i changed the line 85 at jsondb.go to ```globalSetting.EndpointAddress = "x.x.x.x"```. But it would be cool to find out why it's getting an error at fetching the public ip, or set a default value in case of an error cause i can change the public ip later at global settings.

Maybe this info helps you finding the error: This happened only on aarch64/arm64 to me. It also worked like a charm on the armv7 architecture.

cheers

**Comment by Zerogiven** [comment]
Maybe it's ok to set the public ip just to an empty string if an error occurs (shouldn't be much work ;)). Like i said before, i can set it later at the global settings, but i can't set if the app isn't starting.

**Comment by brittondodd** [comment]
The code _should already_ set a value ("N/A") if a public IP could not be found (there must be a consensus vote between three URLs to determine public IP, there's also a timeout in place). While I setup to test this on aarch64, is this something you could reproduce, or has it only happened once? What OS are you using, and do you perhaps have IPv6 enabled?

**Comment by Zerogiven** [comment]
I tried this with the latest raspbian(raspberry os) light and yes i can reproduce it. I tried it with the same raspberry at the same network with both modes, armv7 and aarch64. First works without any problem, second is getting the error "No IP". Does not matter if i use your prebuild or make a new build. For now i had to hard code the ip and build your project by myself to get it running. It's really funny and i saw at the code that this should not happen but i am also not very familiar with the go lang.

Oh and i set at the raspbian os to aarch64 (default is armv7).

https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-01-28/2022-01-28-raspios-bullseye-armhf-lite.zip

I tested all the things at the ui, and it's really just the problem that it is not getting an ip at start, all other things work like a charm.

**Comment by Zerogiven** [comment]
I am not 100% sure about the IPv6 thing, i can take a look at monday at work. But not know why it should get an IPv6 cause like said before if i try your test urls with curl i get the correct IPv4 public ip. Only the calls inside go make any problems...
