### ISSUE TITLE
QR code missing

### ISSUE THREAD

**Issue by marcofrl1603** [ngoduykhanh/wireguard-ui#147]
Hi, I installed the last binary release, work fine but the QR code for clients missing.
There are some library needed to diplay the QR code ?

Thanks a lot

**Comment by ngoduykhanh** [comment]
@marcofrl1603 the recent changes remove the QR from the home page. You need to click on "Scan" button to display it.

**Comment by marcofrl1603** [comment]
Thanks for your speed in the reply.
Yes work... sorry for the issue.

Best regards
-- 
     Marco Fiorletta

SSOLO  Ltd | 20-22 Wenlock Road,N17GU London UK
 
Office: +44 (0)20 8938 3283 | Internal: +44 (0) 8704954880  | Mobile:
+44 (0)7440777545
***@***.*** | www.ssolo.co.uk
 
DISCLAIMER: This email and any files transmitted with it are
confidential and intended solely for the use of the individual or
entity to who they are addressed. If you have received this email in
error please notify the originator of the message.
