### ISSUE TITLE
SMPT

### ISSUE THREAD

**Issue by marcofrl1603** [ngoduykhanh/wireguard-ui#148]
I tried to send client configuration by email using our SMTP server, I set the follow Enviroment variabiles
SMTP_HOSTNAME 10.0.0.5
SMTP_PORT 587
SMTP_USERNAME username of emailserver
SMTP_PASSWORD password
SMTP_AUTH_TYPE PLAIN
EMAIL_FROM_ADDRESS: noreply@ssolo.co.uk
EMAIL_FROM_NAME: SSOLO Info

But the binary try to send the email from 127.0.0.1:25

**Comment by brittondodd** [comment]
This feature was just merged (https://github.com/ngoduykhanh/wireguard-ui/pull/146) I bet the next release might support SMTP mail.

**Comment by do1das** [comment]
![grafik](https://user-images.githubusercontent.com/58998008/157696992-2ca90137-9353-4553-bc53-b3551d470eee.png)
Try -smtp-auth-type "LOGIN"
