### ISSUE TITLE
[bug] SMTP_AUTH_TYPE not working?

### ISSUE THREAD

**Issue by perler** [ngoduykhanh/wireguard-ui#150]
SMTP_AUTH_TYPE seems to accept "Plain" as value (should maybe be in the readme, I had to look at the code) but wireguard-ui doesn't seem to authenticate when sending (I see 554 5.7.1 Relay access denied in the logs of the mailserver).

**Comment by do1das** [comment]
![grafik](https://user-images.githubusercontent.com/58998008/157696473-115eb7ed-d2da-482e-99ca-6730de98d028.png)
Try -smtp-auth-type "LOGIN"
