### ISSUE TITLE
use on dedicated  debian server

### ISSUE THREAD

**Issue by jly26** [ngoduykhanh/wireguard-ui#16]
Hi How can I install this on my debian vps with wireguard server running on it..asking for noob friendly installation procedure..TY

**Comment by jly26** [comment]
thx I download the binary,,hope you we can change admin pass and http port ..and If we can send email to the user with the config and qc code upon creation,,

**Comment by ngoduykhanh** [comment]
You can use either docker or binary file.
You can change the credential in file `./db/server/users.json`. There will be a UI for it in the future releases. And email feature as well.

**Comment by jly26** [comment]
Hi thanks on your binary..So I downloaded 0.2.3 linux version , but on wg ui webpage , still I have 0.1 version.I dont have a preshared key option  on config..
