### ISSUE TITLE
Feature Request: Make Private Keys Optional

### ISSUE THREAD

**Issue by ferrine** [ngoduykhanh/wireguard-ui#160]
Private keys are stored to generate user config. It is preferable to avoid them at all. These features will improve the security model of the UX

* On client generation step ask for an optional public key. If provided, set field of private key to null, otherwise generate a keypair 
* add a button to delete private key and set it to null
* Email can still be generated with private key missing, user responsibility is to replace it on client side

**Comment by ferrine** [comment]
I decided to stay with only one additional proposed feature: specifying public/preshared key. Deletion of private key raised UI concern that needs further discussion

**Comment by SomeoneSerge** [comment]
Just not to spawn too many issues: consider emailing a one-time download link for the config, rather than the config with the plaintext private key

**Comment by ferrine** [comment]
That seems a separate issue
