### ISSUE TITLE
Cannot change admin login/password on Ubuntu Server; not respecting users.json?

### ISSUE THREAD

**Issue by surfrock66** [ngoduykhanh/wireguard-ui#163]
I have wireguard-ui executing from /etc/wgui/wireguard-ui.  Once I run it, it creates a folder structure in there containing "db/server/users.json".  The only user in users.json is "admin/admin".  If I overwrite that file with another username/password, then restart the executable, I still can only log into wireguard-ui via the admin/admin credentials.

Am I doing something wrong here?  Is there a better way to change the login/password?

**Comment by webartifex** [comment]
Hi there, I can confirm the same issue on a fresh install with latest version.

**Comment by bcredeur97** [comment]
This is an issue I'm having as well. Any ideas on how to remediate? Even a temporary workaround?

**Comment by jameswillhoite** [comment]
I'm on Ubuntu 22 and changing this file worked for me

**Comment by basbs** [comment]
I tried to change the default username and password, it works as expected. I can now login with the changed username and password. 

OS version:  Ubuntu 20.04 LTS 
Wireguard-ui binary:  [v0.3.7](https://github.com/ngoduykhanh/wireguard-ui/releases/download/v0.3.7/wireguard-ui-v0.3.7-linux-amd64.tar.gz)

**Comment by surfrock66** [comment]
I am on 22.04, using binary v0.3.7.  I am running this from "/etc/wgui" and in there, the binary is wireguard-ui, and then there is a subfolder "db/server" and I am editing the "users.json" file.  Can I ask what permissions you have in there?  Every file in that folder is 644; for sure only the "admin:admin" credentials are working, the username and password pair I have set in the json file are not being respected.  I am running as the root user and all files are owned by root.

**Comment by jameswillhoite** [comment]
It shouldn't matter, but try restarting the UI after you make the change. I have mine running from ~/wgui as a service. The permission on the file is -rw-r--r-- and the owner:group is james:james for me. The service I have running is running as root:root and I can make the change in there and it sticks.
