### ISSUE TITLE
Adding endpoint config for clients

### ISSUE THREAD

**Issue by jantschaefer** [ngoduykhanh/wireguard-ui#168]
I'm connecting two sites by a wireguard tunnel. In order to get the tunnel working, I have to add the endpoint address of the other wireguard server to the client config in wg0.conf. I tried adding 
```
"endpoint_address": "ip",
"listen_port": "51820"
```
to the client .json file. However, applying the config does not write the endpoint address into the wg0.conf file. I would expect the wg0.conf file to look like this:
```
[Peer]
PublicKey = XX  
AllowedIPs = IPs  
Endpoint = ip:51820
```
Is there a workaround to write the endpoint address to the wg0.conf file for a specific client/peer?

**Comment by ngoduykhanh** [comment]
Unfortunately, there is no way for now as the current implementation is for managing a Wireguard Server that has multiple clients (client-to-site config).

**Comment by mmirik** [comment]
I have built and setup the latest code and use the UI to create a client on my Ubuntu system, with the intention of connecting to another Wireguard UI server.  [jantschaefer](https://github.com/jantschaefer) is correct, without the Endpoint option, the configuration created by the UI does not work.  If you simply added an "Endpoint" option into the client config UI, which was written out into the wg0.conf on "apply config", then this software would work fine to setup and manage the client.

Adding a PersistentKeepalive = ?  option to the client setup would also be useful.

**Comment by montvid** [comment]
Hi guys I need to connect two wireguard servers and without the "Endpoint" option in the UI it is impossible - the wg0.conf gets overwritten and my manual edit vanishes! How to fix this so my manual edit of wg0.conf does not reset? Please add "Endpoint" option to the UI!
