### ISSUE TITLE
Add subnet network behind the client

### ISSUE THREAD

**Issue by a7lan** [ngoduykhanh/wireguard-ui#169]
I sometimes need to add a network behind a client in AllowedIPs in server config like:
[Peer]
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AllowedIPs = 10.89.89.12/32, 172.26.0.0/20

But i cant. I have **error does not belong to any network addresses of WireGuard server**

Now a temporary solution is to manually add to json file in client dir

**Comment by jantschaefer** [comment]
Adding the IPs to "Extra Allowed IPs" should do the trick.

**Comment by a7lan** [comment]
> Adding the IPs to "Extra Allowed IPs" should do the trick.

thx!
