### ISSUE TITLE
Side by Side Config

### ISSUE THREAD

**Issue by Rock4Fun** [ngoduykhanh/wireguard-ui#170]
Hi
is it possible to realize a side by side config? I have a working side by side config which i tried to rebuild by the wireguard-ui. To config the server side works fine. But i can not create the config to act as client.
Thank you

**Comment by ngoduykhanh** [comment]
What do you mean by "side by side config"?

**Comment by Rock4Fun** [comment]
If I have configured the server in wireguard-ui and also created the clients, I can export the clients as a file. I would like to import this file into wireguard-ui on the other server so that wireguard then connects to the previously configured server. I am currently doing this step manually.

**Comment by CrunkFX** [comment]
So, the correct term for this would be Site-to-Site VPN, but +1 for us, we are also very interested in this feature.

**Comment by jantschaefer** [comment]
This is probably related to #168 and requires an option to configure the endpoint from the UI.
