### ISSUE TITLE
Send mail without docker

### ISSUE THREAD

**Issue by marcosmatas** [ngoduykhanh/wireguard-ui#171]
Hello. 

It's possible to send the configurations via email without install wireguard-ui with docker?

I Installed wireguarad-ui directly in a folder. All works fine except sending e-mails. I have the following error

"Mail Error on dialing with encryption type STARTTLS: dial tcp 127.0.0.1:25: connect: connection refused"

I tried installing sSMTP and configuring it, but the message is the same. ¿How can i edit the configuration to send mails?

**Comment by marcosmatas** [comment]
OK. Now I know how I can do it. 

cd /etc
nano environment

and then, i must put some new lines like this: 

SMTP_HOSTNAME="smtp.midominio.com"
SMTP_PORT="587"
SMTP_USERNAME="pepito@midominio.com"
SMTP_PASSWORD="misupercontraseñasupersegura"
SMTP_AUTH_TYPE="LOGIN"
EMAIL_FROM_ADDRESS="pepito@midominio.com"
EMAIL_FROM_NAME="Pepito cantalapiedra"

Restart the system and then all works as expected. 

Thanks. 

PD: Great software!!!

**Comment by ngoduykhanh** [comment]
Yep, it is just a matter of setting the environment variables. 👍
