### ISSUE TITLE
Wireguard-ui behind proxy

### ISSUE THREAD

**Issue by ztjuh** [ngoduykhanh/wireguard-ui#175]
I'm trying to run wireguard-ui behind a nginx proxy, but it doesn't seem to work, here is the output of the log.

`{"time":"2022-03-24T21:58:34.86823435Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":25967,"latency_human":"25.967µs","bytes_in":0,"bytes_out":2}`

**Comment by ngoduykhanh** [comment]
It is just a health check log. There might be something wrong with your Nginx config.
Following is an example of Nginx reverse proxy config that you can use
```
server {
    listen      80;
    server_name example.com;

    location / {
        proxy_pass http://127.0.0.1:5000;

        # Proxy headers
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;
    }
}
```

**Comment by ztjuh** [comment]
Thank you for your reply! 

I have opened up the port on my server and I get a `ERR_CONNECTION_REFUSED`.
