### ISSUE TITLE
Import existing configuration from /etc/wireguard/wg0.conf

### ISSUE THREAD

**Issue by delfer** [ngoduykhanh/wireguard-ui#177]
Server was installed by https://github.com/Nyr/wireguard-install
https://github.com/ngoduykhanh/wireguard-ui do not import anything from /etc/wireguard/wg0.conf
Please, implement importing:
- Address
- PrivateKey
- ListenPort
- MTU
- Peers

It is not necessary to implement comaration of local DB and config file. Just give option what should be used as trust source.
And if wg0.conf is selected and it is already in the format https://github.com/Nyr/wireguard-install, then you need to add to it in the same format.

**Comment by dojo90** [comment]
+1

**Comment by GordonCopestake** [comment]
Would be helpful to just allow editing of the server keys to match the existing config to allow existing clients to still work

**Comment by cgmastertecnology** [comment]
+1
importing peer's .conf too
