### ISSUE TITLE
webgui 0.1

### ISSUE THREAD

**Issue by jly26** [ngoduykhanh/wireguard-ui#18]
Hi thanks on your binary..So I downloaded 0.2.3 linux version , but on wg ui webpage , still I have 0.1 version.I dont have a preshared key option on config

**Comment by ngoduykhanh** [comment]
The version shown on the UI doesn't reflect the actual binary version. I'll fix it in the next release.
The preshared key is auto-generated for your config. You don't need to customize it from UI.

**Comment by jly26** [comment]
ok got it  ty. I have existing keys working now ,if I want to reuse them on wireguard ui ,,but the keys box are not configurable paste your existing keys..any work around??

**Comment by jly26** [comment]
also this:
`
root@dns:/etc/systemd/system# cat wgui.path
[Unit]
Description=Watch /etc/wireguard/wg0.conf for changes

[Path]
PathModified=/etc/wireguard/wg0.conf

[Install]
WantedBy=multi-user.target
root@dns:/etc/systemd/system# cat wgui.service
[Unit]
Description=Restart WireGuard
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/bin/systemctl restart wg-quick@wg0.service
root@dns:/etc/systemd/system# systemctl enable wgui.{path,service}
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
   .wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
   a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
   D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the unit is meant to be enabled with some
   instance name specified.
root@dns:/etc/systemd/system# systemctl start wgui.{path,service}
Job for wgui.service failed because the control process exited with error code.
See "systemctl status wgui.service" and "journalctl -xe" for details.
`

**Comment by nigerninja** [comment]
@jly26 
For this wg0.service not being available, a quick search indicated might be due to older kernels where it is not in systemd. 
My workaround was to call a script performing wg-quick down & wg-quick up on the interface instead of the wg-quick@wg0.service.

Works fine so far.


> also this:
> `
> root@dns:/etc/systemd/system# cat wgui.path
> [Unit]
> Description=Watch /etc/wireguard/wg0.conf for changes
