### ISSUE TITLE
manage multiple configs / servers

### ISSUE THREAD

**Issue by maaathieu-x** [ngoduykhanh/wireguard-ui#180]
Hi,

In my typical deployments, I use two different configs (wireguard interface, private key, user db, listening port) on one physical server, in order order to separate different groups of users (regular user vs admin for example). 
It would be great if wireguard-ui could  manage this scenario. I can't use launch a second process because the the listening port and db directory are hardcoded. 

Mathieu

**Comment by Nill-R** [comment]
Your can use systemd unit and WorkingDirectory for separate two instance wireguard-ui
Change -bind-address for port and WorkingDirectory for dir in my example
Two different units for two instance
```
[Unit]
Description=Wireguard UI
After=network.target

[Service]
Type=simple

# Environment="SENDGRID_API_KEY=YOUR_API_KEY_HERE"
# Environment="EMAIL_FROM_ADDRESS=YOUR_EMAIL_HERE"
# Environment="EMAIL_FROM_NAME=YOUR_NAME_HERE"

ExecStart=/usr/local/bin/wireguard-ui -bind-address 127.0.0.1:5000
WorkingDirectory=/etc/wireguard/ui

Restart=on-failure
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=wireguard-ui

[Install]
WantedBy=multi-user.target
```

**Comment by lightonflux** [comment]
Having two networks/configs is quite common, so it would be nice to see this feature in the future. Currently, the UI is already displaying all WireGuard interface on the status page.

**Comment by gnat** [comment]
**Lame Workaround**

Make a copy of `wireguard-ui` in a different folder (ex: `/root/wg2`), specify a different config and port: `WGUI_CONFIG_FILE_PATH=/etc/wireguard/wg2.conf BIND_ADDRESS=0.0.0.0:5002 ./wireguard-ui`

Would be far better to swap wireguard conf in the UI, though.
