### ISSUE TITLE
Send config through Telegram?

### ISSUE THREAD

**Issue by eignatov** [ngoduykhanh/wireguard-ui#184]
Hello.
Can you please implement sending config and qr through Telegram using telegram chat_id??

**Comment by Nill-R** [comment]
As a temporary solution, you can use [SMTP to Telegram](https://github.com/KostyaEsmukov/smtp_to_telegram)

**Comment by antedebaas** [comment]
From a security standpoint I would not send configs trough a 3rd party (or smtp for that matter)
SSH is far safer
