### ISSUE TITLE
SMTP authentication

### ISSUE THREAD

**Issue by marcofrl1603** [ngoduykhanh/wireguard-ui#187]
Hi, is possible to add the support for self signed certificate?

Mail Error on STARTTLS: x509: cannot validate certificate for 10.0.0.5 because it doesn't contain any IP SANs

Thanks

**Comment by jamiepaugh** [comment]
I am also having this issue after configuring postfix and setting the environment variables (/etc/environment).

**Comment by ymrsmns** [comment]
Add settings 

```
    environment:
      .....
      - SMTP_NO_TLS_CHECK=true
```

https://github.com/ngoduykhanh/wireguard-ui/blob/87b08a8f7c026e325438b18a1d7384fd33847e5c/main.go#L59
