### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by Slyke** [ngoduykhanh/wireguard-ui#188]
Hello, I have a Wireguard pod running on my K8s cluster, and also this running as a pod on my K8s cluster. I can connect just fine to the standard Wireguard pod, but when I try to connect to this one, the server never replies. They use the same networking templates and are executed on the same nodes.

I've noticed some differences with the wg0.conf files, even though I tried making them the same:

Wireguard-UI:
```
[Interface]
Address = 10.13.13.0/24
ListenPort = 51820
PrivateKey = XXXXXXXXXXXXXXXXXXXXXXXXXXX
MTU = 1450
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -A POSTROUTING -o eno1 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -D POSTROUTING -o eno1 -j MASQUERADE

[Peer]
PublicKey = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
PresharedKey = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AllowedIPs = 10.13.13.1/24
```

Standard Wireguard:
```
[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = XXXXXXXXXXXXXXXXXXXXXXXXXX
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -A POSTROUTING -o eno1 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -t nat -D POSTROUTING -o eno1 -j MASQUERADE

[Peer]
# peer1
PublicKey = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AllowedIPs = 10.13.13.2/32

[Peer]
# peer2
PublicKey = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AllowedIPs = 10.13.13.3/32

... more peers
```

The main difference between these 2 configs is the `Address` under `Interface`. Wireguard UI requires that a network mask be provided in the UI, but the standard Wireguard does not. Wireguard UI also requires that the `AllowedIPs` IP address lies within the same subnet as the `Interface` `Address`, where's standard Wireguard does not.

When checking the logs on the mobile app, I can see that data is being sent, but none is received. There's also "Sending handshake initiation" but shortly after "Handshake did not complete after 5 seconds".

I never see any clients connected in the Status page either. There are no errors on the pod logs.

**Comment by ngoduykhanh** [comment]
The configs look good to me. Since they are in the same network (using the same /24 netmask), they should be able to communicate. Please try to tune the MTU size, it could be a problem when running in K8s environment where an overlay network exists.

**Comment by Slyke** [comment]
My home network is running on 10.7.0.0/16, so I tried setting the Server Interface Address to that, setting my Peer's IP Allocation to 10.7.3.5/16, applying the config and finally rescanning the QR code, but it still didn't work. I also decreased the MTU down to 512 as well, but also didn't work.

Is it possible to have Wireguard on its own network (like `10.13.13.0/24`)? I want to be able to selectively add routes or NATs to my LAN network. The UI doesn't seem to allow for this type of config.

**Comment by cgmastertecnology** [comment]
> My home network is running on `10.7.0.0/16`, so I tried setting the Server Interface Address to `10.7.0.0/16` and `10.7.60.12/16` (the IP of the actual node the pod is on) independently, setting my Peer's IP Allocation to `10.7.3.5/16`, applying the config and finally rescanning the QR code, but it still didn't work. I also decreased the MTU down to 512 as well, but also didn't work.
> 
> Is it possible to have Wireguard on its own network (like `10.13.13.0/24`)? I want to be able to selectively add routes or NATs to my LAN network. The UI doesn't seem to allow for this type of config.

hello same problem here, standard wireguard works but wireguard UI doesn't work
did you solve the issue?

**Comment by Slyke** [comment]
@cgmastertecnology nope, still not able to get it to work.

**Comment by Slyke** [comment]
Not stale. Issue is still outstanding.

**Comment by ngoduykhanh** [comment]
Were your moble-client able to reach 10.13.13.1 (server IP address)? It is a private IP address though.
You can also try adjusting the generated-config to be the same as the "standard Wireguard" setup to verify if it was a real issue with the config.

**Comment by Slyke** [comment]
Nope, I can see Wireguard attempting to send data, but nothing ever comes back. Yep, it's the remote Wireguard VPN's IP.

**Comment by Slyke** [comment]
Not stale. Issue is still outstanding.

**Comment by sinbino** [comment]
Why doesn't wireguard-ui accept the "Standard Wireguard" setting?
