### ISSUE TITLE
Invalid QR Code 

### ISSUE THREAD

**Issue by ecsuae** [ngoduykhanh/wireguard-ui#190]
I am facing strange problem ,if I try to scan qr code on android or iOS ,I get error invalid wireguard configuration.Can you help how to fix they problem?If I scan the code from wireguard_ui webpage it works fine ,if I download it and scan it it is not working.I tried to take screenshot of the code as well but still same problem.Can someone guide what is wrong?

**Comment by ngoduykhanh** [comment]
I don't quite get it. Do you mean it didn't work when you scanned the QR code that was displayed on the mobile phone, but it worked for the ones displayed on the PC?
Try to download file config file and compare them (working v.s not working client) to see if there is any difference in the format.

**Comment by ecsuae** [comment]
Thanks for the prompt update.problem is fixed ,it was due to a setting
Forward Mark 0xca6c
before the value was empty and it was showing 
FwMark =
in the conf file, after setting the value to 0xca6c ,the problem is gone.

**Comment by ngoduykhanh** [comment]
Thanks for reporting. I made a PR to address the issue.
