### ISSUE TITLE
Empty wireguard installation $VER-linux-amd64.tar.gz with 1kb size is downloaded

### ISSUE THREAD

**Issue by vtec99** [ngoduykhanh/wireguard-ui#194]
############

Hello everyone, since 2.05.22 I have a problem when installing the flat on Linux Debian 11/Ubuntu.
The download of the installation file for Wireguard configuration is downloaded "empty" with only 1 kb to the VPS with Linux:
  wireguard-ui--linux-amd64.tar.gz
  wireguard-ui-v0.3.7-linux-amd64.tar.gz

The problem is when executing the update.sh "Creating the wireguard ui download and update script".

An empty wireguard installation $VER-linux-amd64.tar.gz with 1kb size is probably downloaded.
This can no longer be extracted logically:

cd /etc/wireguard; ./update.sh
downloading wireguard-ui
extracting tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
restarting wgui-web.service

#####################################
#My Script: WireGuard UI

#First we create the Systemd Service Unit.

cat <<EOF > /etc/systemd/system/wgui-web.service

[Unit]
Description=WireGuard UI
 
[Service]
Type=simple
ExecStart=/etc/wireguard/start-wgui.sh
 
[Install]
WantedBy=multi-user.target
EOF

#WireGuard UI Download and Update Script:

cat <<EOF > /etc/wireguard/update.sh
 
#!/bin/bash
 
VER=\$(curl -s https://github.com/ngoduykhanh/wireguard-ui/releases/latest | cut -d "/" -f8 | cut -d "\"" -f1)
 
echo "downloading wireguard-ui \$VER"
curl -sL "https://github.com/ngoduykhanh/wireguard-ui/releases/download/\$VER/wireguard-ui-\$VER-linux-amd64.tar.gz" -o wireguard-ui-\$VER-linux-amd64.tar.gz
 
echo -n "extracting "; tar xvf wireguard-ui-\$VER-linux-amd64.tar.gz
 
echo "restarting wgui-web.service"
systemctl restart wgui-web.service
EOF

#Now we can run the Wireguard UI Update Script for the first time. The download starts automatically and Wireguard's web interface is started.

chmod +x /etc/wireguard/update.sh
cd /etc/wireguard; ./update.sh

 #####################################

Error:

cd /etc/wireguard; ./update.sh
downloading wireguard-ui
extracting tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
restarting wgui-web.service

**Comment by gdcooman** [comment]
This should work:
`VER=$(curl -ILs -o /dev/null -w %{url_effective} https://github.com/ngoduykhanh/wireguard-ui/releases/latest | cut -d "/" -f8)`

**Comment by vtec99** [comment]
TOP, Thank you ;)
