### ISSUE TITLE
Additional Configuration Options

### ISSUE THREAD

**Issue by nigerninja** [ngoduykhanh/wireguard-ui#20]
Good work on the GUI binary, works as currently advertised.
It would be nice to be able to include additional configurations (e.g. PostUp & PostDown) in the conf files generated. Either Manually or via the GUI would be fine i believe, however, currently any change made manually to the conf file is overwritten by the GUI.
Any workaround? Or can this feature be added?

Thanks.

**Comment by zachberger** [comment]
PostUp and PostDown would be great for configuring NAT

**Comment by nigerninja** [comment]
@zachberger Yes it is, have 2 scripts for these now. But as an enhancement would be a nice thing to have :)


> PostUp and PostDown would be great for configuring NAT

**Comment by jarylc** [comment]
@nigerninja @zachberger do try https://github.com/ngoduykhanh/wireguard-ui/pull/28 out if you have the opportunity to and let me know if it's good.

I have an exported docker image downloadable here too: https://drive.google.com/file/d/1annHkDeyXGUwYMN5hl2RisUOBpFhQIre/view?usp=sharing

You can import the above image into docker by using:
```bash
docker load -i "/path/to/wgui.tar"
```

@ngoduykhanh are you accepting pull requests?

**Comment by Fastidious** [comment]
If `PostUp` and `PostDown` already exist--or are added manunally--to the configuration file, will they be stripped out by *wireguard-ui*? If not, this is not a biggie.

**Comment by Fastidious** [comment]
I just tested it, it doesn't read an existing `wg0.conf` at all. That's no... good.

**Comment by jarylc** [comment]
> If `PostUp` and `PostDown` already exist--or are added manunally--to the configuration file, will they be stripped out by _wireguard-ui_? If not, this is not a biggie.

Yes, to my understanding it will be overwritten according to the codes. May be wrong though, never tested that.

> I just tested it, it doesn't read an existing `wg0.conf` at all. That's no... good.

This issue is only for additional config options, parsing wg0.conf will probably require more work, maybe it's down the pipeline.

**Comment by ngoduykhanh** [comment]
I merged the PR from @jarylc for `PostUp` and `PostDown`.
For now, the Wireguard-UI will simply override/generate a new config file, depends on the path you set in the setting. Reading from an existing config file will need more work to handle several cases that I am not going to include it now in the project.

**Comment by nigerninja** [comment]
@jarylc Thanks! Would update & try it out in a couple of days, in the middle of a project right now. :+1:
