### ISSUE TITLE
Existing WG config is not parsed

### ISSUE THREAD

**Issue by gerroon** [ngoduykhanh/wireguard-ui#202]
Hi

I am using the docker-compose  on a Debian system that has WG installed and running, so /etc/wireguard already exists and it is already defined in thee compose file like that. When I up the docker-compose, I do not see the existing clients/settings under "WireGuard Clients" whatsoever. Is this not supported?

The status panel seems to list the clients but I cant do anything with that page.

**Comment by maximko** [comment]
Can confirm this.
