### ISSUE TITLE
Proxmox LXC Container

### ISSUE THREAD

**Issue by capelo0** [ngoduykhanh/wireguard-ui#215]
Hi, I'm quite noob on this and didn't want to use docker but a LXC container. 

Anyone could explain how, if possible, I could install wireguard-ui in a container?
I've deployed a TurnKeyLinux with WireGuard, and would like to understand how I could add this UI to it. 

I really appreciate your help.

**Comment by blockiyt** [comment]
I don't know if it is the most performant way, but just install docker with compose plugin in your LXC, enable nesting and keyctl in proxmox for the lxc, if not already done, and run the ui over docker. That would be my way how I set It up running. But I don't know how to integrate the UI into TurnKeyLinux, if that was your question.

I hope this helps and I did not misunderstood your Issue.

**Comment by capelo0** [comment]
Thanks @blockiyt 

I ended deleting that TKL and creating a simple one with just wg-easy. It was really simple and works like a charm.
