### ISSUE TITLE
Inconsistent interface address between wireguard-ui and wg.conf

### ISSUE THREAD

**Issue by zachberger** [ngoduykhanh/wireguard-ui#22]
How does wireguard-ui determine the server's interface address? In wireguard-ui it seems to detect `10.252.1.0/24`, however `ip a` it shows `wg0` as `192.168.2.1/24`. `192.168.2.1/24` is what I previously had in my `wg.conf`before trying wireguard-ui and what I would expect wireguard-ui to show.

**Comment by zachberger** [comment]
It seems that my existing DNS settings from wg.conf are not respected either. My wg.conf file has 192.168.86.10 and 192.168.86.11 as the DNS servers however wireguard-ui is showing 1.1.1.1 as the DNS server.

**Comment by ngoduykhanh** [comment]
The current implementation doesn't support to load the config from an existing file. We might have it in the future .
