### ISSUE TITLE
Feature Request: https-support

### ISSUE THREAD

**Issue by petterpet** [ngoduykhanh/wireguard-ui#220]
Is it possible to access the web-ui via https with a custom ssl-certificate?

**Comment by snax44** [comment]
What about listening on localhost:5000 only and use nginx or apache2 as proxy with your own certificates ?

**Comment by petterpet** [comment]
This might be possible, yes. But how to configure to only listen on localhost?

And why setting up a second webserver instead of only enableling SSL?

**Comment by snax44** [comment]
You can run wireguard-ui with the parameter `-bind-address`:
```
wireguard-ui -bind-address 127.0.0.1:5000
```
There are many reason for doing the latter: not having to run your Go program as root, serving other websites/services on the same host, TLS encryption, load balancing, logging, etc.

**Comment by ngoduykhanh** [comment]
The SSL termination can be done at a reverse proxy (e.g. Nginx) or Load Balancer level. I think it is a better way.
