### ISSUE TITLE
Consdier only storing keys in wg.conf

### ISSUE THREAD

**Issue by zachberger** [ngoduykhanh/wireguard-ui#23]
After looking at the db folder I see my keys are stored in plain text. Ideally the keys would only be stored in wg.conf which is locked down appropriately.

**Comment by ngoduykhanh** [comment]
Yes, for now, it is just simple like that. We don't have any method for encoding or encrypting atm. Any suggestion?

**Comment by ngoduykhanh** [comment]
Another solution is we don't store the key in the DB. But then we have to use the same existing key in wg.conf when we update the file.
