### ISSUE TITLE
FreeBSD rc.d startup script

### ISSUE THREAD

**Issue by ivomarino** [ngoduykhanh/wireguard-ui#230]
For FreeBSD I created a small rc.d startup script which can be placed in `/usr/local/etc/rc.d/wireguard-ui`, maybe it can be useful to someone:

```
#!/bin/sh
#
# PROVIDE: wireguard_ui
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable wireguard_ui:
#
# wireguard_ui_enable="YES"
#

. /etc/rc.subr

name="wireguard_ui"
rcvar=wireguard_ui_enable
pidfile="/var/run/wireguard_ui.pid"
wireguard_ui_chdir="/usr/local/opt/wireguard-ui"
wireguard_ui_env_file="/usr/local/opt/wireguard-ui/env"

command="/usr/sbin/daemon"
command_args="-r -P {pidfile} -f /usr/local/opt/wireguard-ui/wireguard-ui"

stop_postcmd="wireguard_ui_poststop"

wireguard_ui_poststop()
{
    rm -f $pidfile
}

load_rc_config ${name}

: ${wireguard_ui_enable="NO"}
: ${wireguard_ui_pidfile="/var/run/${name}.pid"}

run_rc_command "$1"
```

This script expects the following folder structure:

```
➜  ~ tree -a /usr/local/opt/wireguard-ui/

/usr/local/opt/wireguard-ui/
├── db
│   ├── clients
│   │   └── cclinskvh744cvio8rhg.json
│   ├── server
│   │   ├── global_settings.json
│   │   ├── interfaces.json
│   │   ├── keypair.json
│   │   └── users.json
│   └── wake_on_lan_hosts
├── env
└── wireguard-ui
```

The `env` contains environment variables, example:

```
WGUI_PASSWORD="<whatever>"

SMTP_HOSTNAME="<whatever>"
SMTP_PORT="587"
SMTP_USERNAME="<whatever>"
SMTP_PASSWORD="<whatever>"
SMTP_NO_TLS_CHECK="true"
SMTP_AUTH_TYPE="LOGIN"

EMAIL_FROM_ADDRESS="<whatever>"
EMAIL_FROM_NAME="<whatever>"
```

In `/etc/rc.conf` you just put `wireguard_ui_enable="YES"` to start the service.

**Comment by ivomarino** [comment]
at this point I have a question, as far as I'm running wireguard-ui in a jail, and wireguard on the real host, do I need to pass in `/dev/wg0` into the jail to be able to see the actual connected clients? Thanks

**Comment by krolingo** [comment]
> at this point I have a question, as far as I'm running wireguard-ui in a jail, and wireguard on the real host, do I need to pass in `/dev/wg0` into the jail to be able to see the actual connected clients? Thanks

I edited your rc.d script to work on my FreeBSD server as follows:

#!/bin/sh
#
# PROVIDE: wireguard_ui
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable wireguard_ui:
#
# wireguard_ui_enable="YES"
#

. /etc/rc.subr
name="wireguard_ui"
rcvar=wireguard_ui_enable
procname="/usr/local/opt/wireguard-ui/wireguard-ui"
pidfile="/var/run/wireguard_ui.pid"
wireguard_ui_chdir="/usr/local/opt/wireguard-ui"
wireguard_ui_env_file="/usr/local/opt/wireguard-ui/env"

command="/usr/sbin/daemon"
command_args=" -s notice -p ${pidfile} -f ${procname} ${wireguard_ui_env_file}"

stop_postcmd="wireguard_ui_poststop"

wireguard_ui_poststop()
{
    rm -f $pidfile
}

load_rc_config ${name}

: ${wireguard_ui_enable="NO"}
: ${wireguard_ui_pidfile="/var/run/${name}.pid"}

run_rc_command "$1"

- - - - - - - 
- I get to stop and start the service with the edited script.
