### ISSUE TITLE
can not change the username&password

### ISSUE THREAD

**Issue by Cryptohardy** [ngoduykhanh/wireguard-ui#231]
once I setup the image (docker-compose up -d) , then I change the WGUI_NAME in the YAML file , and rebuild it using (docker-compose build) the login credentials do not change , What are the proper instructions to do it?

**Comment by ngoduykhanh** [comment]
maybe try deleting the `./db/server/users.json` file and bring up your docker container again?

**Comment by Cryptohardy** [comment]
issue solved , no need to follow the top steps , I just need to modify the users.json file
