### ISSUE TITLE
How to see connected peers while running non root user?

### ISSUE THREAD

**Issue by hurelhuyag** [ngoduykhanh/wireguard-ui#232]
I'm running this software on a non-root user because of security reasons. But I can't see connected peers. 'operation not permitted' message is shown. 
What command should I allow my wgui running user to see connected peers?

**Comment by ngoduykhanh** [comment]
The user who runs `wireguard-ui` needs to have access to the network setting to fetch "connected peers" information. It depends on the operation system I think.

Maybe you can try adding the user to `netdev`group?
Ref: https://askubuntu.com/questions/341810/add-user-to-group-which-can-access-network-interfaces

**Comment by hurelhuyag** [comment]
In my case, it is the ubuntu server 22.04. Currently running user is wgui. I tried the below commands and had no success.

```
usermod -aG netdev wgui
newgrp
service wireduard-ui restart
gpasswd -a wgui netdev
newgrp
service wireduard-ui restart
```

**Comment by ivomarino** [comment]
Is FreeBSD supported to show connected peers? Everything else works fine. Thanks

**Comment by krolingo** [comment]
> Is FreeBSD supported to show connected peers? Everything else works fine. Thanks

I have this question as well.

**Comment by krolingo** [comment]
I still have this question.

**Comment by esmoyer** [comment]
I'm curious on this as well. Just got this installed with OPNsense but OPNsense doesn't seem to pick up on peers.

**Comment by pinhead84** [comment]
Adding

```ini
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN
```

to my systemd service file solved the problem for me.

Here my complete service file, that starts WGUI - of course needs adjustments according to your system:

```ini
[Unit]
Description=Wireguard UI
After=network-online.target

[Service]
ExecStart=/home/vpn/bin/wireguard-ui.sh
WorkingDirectory=/home/vpn
AmbientCapabilities=CAP_NET_ADMIN
CapabilityBoundingSet=CAP_NET_ADMIN
User=vpn
Group=vpn
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by pinhead84** [comment]
This unit file looks like an even better solution to me: <https://aur.archlinux.org/cgit/aur.git/tree/wireguard-ui.service?h=wireguard-ui>

```ini
[Unit]
Description=A web user interface to manage your WireGuard setup
Documentation=https://github.com/ngoduykhanh/wireguard-ui
ConditionPathExists=/var/lib/wireguard-ui
After=network.target

[Service]
Type=simple
User=wireguard-ui
Group=wireguard-ui

CapabilityBoundingSet=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW
AmbientCapabilities=CAP_DAC_READ_SEARCH CAP_NET_ADMIN CAP_NET_RAW

WorkingDirectory=/var/lib/wireguard-ui
EnvironmentFile=-/etc/wireguard-ui/environment.conf
ExecStart=/usr/bin/wireguard-ui

Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Cheers!
