### ISSUE TITLE
Connecting, but not transmitting data

### ISSUE THREAD

**Issue by Fiji05** [ngoduykhanh/wireguard-ui#233]
I have installed wireguard-ui via docker and am running it in docker compose. I have used the default configurations, and have put it behind an apache2 reverse proxy so that it can be accessed when I am not on my local network. 

My issue is this - I am able to connect to the VPN, however, it does not continue to transmit data and my internet just stops working.
<img width="1179" alt="Screen Shot 2022-09-30 at 12 19 21 PM" src="https://user-images.githubusercontent.com/66295742/193323416-9e39e663-652a-4043-b182-e2ed8830432c.png">

**Comment by alex27riva** [comment]
I have the same issue, how did you fix?
