### ISSUE TITLE
Question: Is there a way to configure default values for the binary executable?

### ISSUE THREAD

**Issue by omega0verride** [ngoduykhanh/wireguard-ui#234]
Is there a way to set variables such as the server interface address for the executable without having to modify the JSON? This would be great for automated setups.

**Comment by omega0verride** [comment]
Actually, the exported environment variables are detected when running using go. It is the binary that does not recognize them. Am I doing something wrong or is the binary release outdated?

**Comment by omega0verride** [comment]
Apparently, local builds work fine. Can we expect a new release anytime soon?

**Comment by sorcer1122** [comment]
@omega0verride can you please explain how you achieved this? Wanna build locally, without docker but cannot find how to feed my variables to it.
