### ISSUE TITLE
Make Pre-Shared Keys Optional

### ISSUE THREAD

**Issue by WillMW02** [ngoduykhanh/wireguard-ui#235]
In my set up, forwarding traffic only works when there is not a PSK present, as this feature is optional in Wireguard, it would be useful if it was also optional within this UI to allow for more versatility. Currently I'm having to manually modify client configs before use to remove the PSK.

**Comment by MaffooClock** [comment]
As a workaround that keeps you from having to edit the wg0.conf file after every update, you could modify the `templates/wg.conf` and change this line:
`{{if .Client.PresharedKey }}PresharedKey = {{ .Client.PresharedKey }}
{{end}}`

to:
`{{if .Client.PresharedKey }}#PresharedKey = {{ .Client.PresharedKey }}
{{end}}`

That way, the non-optional PSK ends up being commented out.

**Comment by ngoduykhanh** [comment]
Closing in favor of #271
