### ISSUE TITLE
snax44

### ISSUE THREAD

**Issue by nigelfer2020** [ngoduykhanh/wireguard-ui#239]
Hello,

First of all, thank you for great script to run everything with one click.

I just tried https://gitlab.com/snax44/wireguard-ui-setup/
and installed by:
bash <(curl -s https://gitlab.com/snax44/wireguard-ui-setup/-/raw/master/install.sh)

everything installed without any error and status of wireguard is active.
But to access from web, I still not able to get access via SERVERIP:5000

Could you please exactly explain, how I can get access to web UI from PUBLIC IP (not 127.0.0.1 or localhost).

Please list all commands or steps after installation.

Thank you.

**Comment by snax44** [comment]
Hi @nigelfer2020,

Not necessary to post 3 times :)
I answered [here](https://github.com/ngoduykhanh/wireguard-ui/issues/54#issuecomment-1274216219) and [here](https://github.com/snax44/wireguard-ui-setup/issues/1)

This issue can be closed.
