### ISSUE TITLE
First pageload fails

### ISSUE THREAD

**Issue by zachberger** [ngoduykhanh/wireguard-ui#24]
After the first startup, while loading the webpage the first time, the page crashes complaining the `db` folder doesn't exist. The application should handle this more gracefully.

**Comment by zachberger** [comment]
`"Cannot get client list: stat db/clients.json: no such file or directory"`

**Comment by ngoduykhanh** [comment]
I guess you are using the binary version.
Yes, I confirm this. I didn't notice this error before. Will be fixed in the next release.

**Comment by amiroffme** [comment]
Same issue following...
