### ISSUE TITLE
Feature Request - Add an environment variable/cli argument to specify if we need to "Apply Config" on startup.

### ISSUE THREAD

**Issue by omega0verride** [ngoduykhanh/wireguard-ui#241]
As far as I noticed there is no way to parse an existing WireGuard config file. 
The UI will automatically generate new keys which will differ from the existing file. I can pass other properties like WGUI_SERVER_LISTEN_PORT and WGUI_SERVER_INTERFACE_ADDRESSES through env variables but there is no way to pass the private and public keys.
It would be great if we could either:
1. pass the keys
2. have an option to "Apply Config" on startup this way we can use the generated keys

This can help automate the installation.

**Comment by WaaromZoMoeilijk** [comment]
Ok, apply the config in the webui once while having your browsers dev console open (network tab)

and search for 'apply config' after pressing it. 
Once found, right click, copy curl and you have your curl command to automate everything.

```curl 'http://127.0.0.1:5000/api/apply-wg-config' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -H 'X-Requested-With: XMLHttpRequest' -H 'Origin: http://127.0.0.1:5000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://127.0.0.1:5000/wg-server' -H 'Cookie: session=token =; session_token=token' -H 'Content-Length: 0'
```

**Comment by the-nicolas** [comment]
Just came here to write the same ticket...

- We setup the whole wireguard and wireguard-ui server via Terraform and inject some initial (or backup) of the "db" mount.
- That is on another disk and kept persistent, but during re-setup we loose our /etc/wireguard/*

It would be so good to just have some ENV for "Apply config on startup". The hack with curl is not really nice and I also have no idea if it works at all with a fresh installation. Is the cookie after a restart still valid?

**Comment by the-nicolas** [comment]
Just tested it, doesn't work... The Cookie is invalid after reinstall with restored db-folder an same config...

In general the "API way" via curl is fine, but then something like "Static API-Key" in the request would be necessary. But idea is not so bad, because it would allow also to create new users etc. via API - and perhaps also write some tiny terraform provider for it. That would allow a way better integration of wireguard server via wireguard-ui as central management instance.
