### ISSUE TITLE
Issues loading correct values when running standalone binary?

### ISSUE THREAD

**Issue by liamlows** [ngoduykhanh/wireguard-ui#245]
Hey,

So I recently installed the binary standalone and when i access the web interface it picks up my existing clients under the status page but i don't see them under the wireguard clients page. Also the wireguard server settings page doesn't show the correct information that is set in /etc/wireguard/wg0.conf. It also doesnt respect the environment variables i set in the conf below.

I have wireugard-ui installed as `/bin/wireguard-ui` and created the following systemd service (`/etc/systemd/system/wgui_http.service`) that is enabled:

    [Unit]
    Description=Wireguard UI
    After=network.target
    
    [Service]
    Type=simple
    Environment="WGUI_SERVER_INTERFACE_ADDRESSES=[my wg subnet]"
    Environment="WGUI_PASSWORD=[Password]"
    WorkingDirectory=/bin/
    ExecStart=/bin/wireguard-ui
    
    [Install]
    WantedBy=multi-user.target

it outputs this when it runs:

    Oct 19 06:03:47 wireguard wireguard-ui[1857]: App Version        : v0.3.7
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Git Commit        : ad4ca4d9bb344236a2793fee54ec24cf07d6cd8c
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Git Ref                : refs/tags/v0.3.7
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Build Time        : 10-19-2022 06:03:47
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Git Repo        : https://github.com/ngoduykhanh/wireguard-ui
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Authentication        : true
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Bind address        : 0.0.0.0:5000
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Email from        :
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: Email from name        : WireGuard UI
    Oct 19 06:03:47 wireguard wireguard-ui[1857]: ⇨ http server started on [::]:5000

I also have:

    # wgui.service
    [Unit]
    Description=Restart WireGuard
    After=network.target
    
    [Service]
    Type=oneshot
    ExecStart=/usr/bin/systemctl restart wg-quick@wg0.service
    
    [Install]
    RequiredBy=wgui.path

and 

    # wgui.path
    [Unit]
    Description=Watch /etc/wireguard/wg0.conf for changes
    
    [Path]
    PathModified=/etc/wireguard/wg0.conf
    
    [Install]
    WantedBy=multi-user.target

Anyone know what I might be doing wrong?

**Comment by liamlows** [comment]
Update:

I have altered my install and now the executable is in `/opt/wgui` and then linked it to `/usr/local/bin`. My systemd file now looks like this:

    [Unit]
    Description=Wireguard UI
    After=network.target
    
    [Service]
    Type=simple
    Environment="WGUI_SERVER_INTERFACE_ADDRESSES=[my wg subnet]"
    Environment="WGUI_PASSWORD=[Password]"
    WorkingDirectory=/bin/
    ExecStart=/bin/wireguard-ui
    
    [Install]
    WantedBy=multi-user.target

However, the issue still stands that the information under the "wireguard clients" and "wireguard server" pages does not match the current server configuration. Is there an easy way to import the existing server configuration for wireguard-ui?

**Comment by nskillen** [comment]
Not sure if you've got it figured out yet, and it's been long enough that you may well have given up if you didn't work it out. But, if you haven't, and you're still trying, I think the following may help out:

You said you're now keeping wireguard-ui in `/opt/wgui`, and you've symlinked the executable into `/usr/local/bin`. In that case, I'd suggest a unit file that looks like this:
```service
[Unit]
Description=Wireguard UI
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/wgui
ExecStart=/usr/local/bin/wireguard-ui

[Install]
WantedBy=multi-user.target
```
This will cause wireguard-ui to run out of the `/opt/wgui` folder, and from what I can tell the env vars are only needed on first boot, after that they're written into the config files and pulled from there.

This, by itself, won't fix the information on the pages though. Next you'll want to look in your `/bin` folder, and you'll probably see a folder named `db`. If `/bin/db` is present and contains the subfolders `clients, server, wake_on_lan_hosts` then that is your data store for wireguard-ui. Stop the service via
```sh
systemctl stop wgui_http.service
```
and then move the db to its new home via
```sh
mv /bin/db /opt/wgui/
```
(replace `/bin/db` with wherever the db is actually located)

Once you've done that, if you go looking in each folder, you'll see that everything is just json files. If you dig through there it's pretty straightforward to work out what information goes where, and you'll be able, I suspect, to edit the files to show the information you'd like to see.

Alternatively, simply load things up the way it currently is, and edit in the UI to match your wg0.conf. The only values you can't change are the server key, but you can edit that in `./db/server/keypair.json`.

For the clients, there's one file in `./db/clients` per client configured. They look like this:
```json
{
        "id": "some-string-i-dont-know-how-its-made",
        "private_key": "the-clients-private-key",
        "public_key": "the-clients-public-key",
        "preshared_key": "a generated client has a preshared key",
        "name": "client-name",
        "email": "client-email",
        "allocated_ips": [
                "x.x.0.2/32"
        ],
        "allowed_ips": [
                "x.x.0.0/24",
        ],
        "extra_allowed_ips": [],
        "use_server_dns": true,
        "enabled": true,
        "created_at": "1977-05-13T06:51:28.779914443Z",
        "updated_at": "1977-05-13T06:51:28.779914443Z"
}
```
and the file is named `<id-value>.json`. As mentioned, I don't know where that value comes from, so I can't help you work out what goes there. It might be random, you could try putting junk in there and see if it works.

Don't forget to reload your systemd unit files, and restart the UI!
```sh
systemctl daemon-reload
systemctl start wgui_http
```
