### ISSUE TITLE
Non-Docker version?

### ISSUE THREAD

**Issue by martin-g-it** [ngoduykhanh/wireguard-ui#247]
Hi, is there also a non-docker version of this package?
Maybe I'm missing something, but I have WireGuard running in a LXC container on Proxmox and like to keep this container as lean as possible.

**Comment by michaeldouble07** [comment]
Yes, you can go to [](https://github.com/ngoduykhanh/wireguard-ui/releases/tag/v0.3.7) and use wget to get the proper architecture. then all you do is run the `./wireguard-ui` command to where you have un-tar'd the file.

**Comment by martin-g-it** [comment]
Thanks! in the end went for the WG Dashboard which seems to be a bit better (not messing up with existing configuration)
