### ISSUE TITLE
wireguard-ui with proxmox lxc & email(smtp)

### ISSUE THREAD

**Issue by Troox73** [ngoduykhanh/wireguard-ui#249]
I'm searching the internet for hours... Can anyone please explain how to setup the email configuration to send qrcode via smtp (gmail). I dont get it where to setup this config. Is it a plain textfile with name ENV inside the directory where wireguard-ui executable life in? thanks!

**Comment by psycho-dad** [comment]
edit your /etc/wireguard/start-wgui.sh like this:

`#!/bin/bash

export SMTP_HOSTNAME="smtp.gmail.com"
export SMTP_PORT="587"
export SMTP_USERNAME="JOURMAIL@gmail.com"
export SMTP_PASSWORD="****password****"
export SMTP_AUTH_TYPE="LOGIN"
export EMAIL_FROM_ADDRESS="JOURMAIL@gmail.com"
export EMAIL_FROM_NAME="WireGuard-UI"

cd /etc/wireguard
./wireguard-ui -bind-address 0.0.0.0:8080`

**Comment by Troox73** [comment]
Thanks! Will try it later and report back :)

**Comment by Alex-joomla** [comment]
tried this but get always this error:

**Mail Error: mail: invalid string; Header: [From] Address: [WireGuard UI <>]**

**Comment by Forsskieken** [comment]
**This works..**
root@Wireguard:/opt/wireguard-ui# ./wireguard-ui
Wireguard UI
App Version     : v0.4.0
Git Commit      : be2ffba4176cdee99e46be79ceb7afe075a6195f
Git Ref         : refs/tags/v0.4.0
Build Time      : 03-31-2023 21:54:34
Git Repo        : https://github.com/ngoduykhanh/wireguard-ui
Authentication  : true
Bind address    : 0.0.0.0:5000
Email from      : my.emailgmail.com
Email from name : WireGuard UI
Custom wg.conf  : 
Base path       : /
⇨ http server started on [::]:5000

/etc/environments
SMTP_ENCRYPTION=STARTTLS
SMTP_HOSTNAME=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=my.email@gmail.com
SMTP_PASSWORD=sfgpqwsavjcsmkqqq  : generated in App passwords of Google
SMTP_AUTH_TYPE=LOGIN
EMAIL_FROM_ADDRESS=my.email@gmail.com
EMAIL_FROM_NAME=Wireguard Ui

**Comment by Forsskieken** [comment]
Hi,
I noticed that a working configuration doesn't work when the container is restarted
One need to systemctl stop wireguar-ui
one need to cd /opt/wireguard-ui
one need to start at that path ./wireguard-ui then it works
