### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by lukash138** [ngoduykhanh/wireguard-ui#253]
I compiled from source and used envinronment variables in service unit file - it works OK. I mentioned the version is marked as development so I wanted to switch to stable. When i downloaded compiled 0.3.7 and replaced binary file with it, the environment variables are not noticed.

[Unit] 
Description=WireGuard UI                                                                                                Documentation=https://github.com/ngoduykhanh/wireguard-ui   
After=network.target network-online.target 
Requires=network-online.target                                                                                          AssertFileIsExecutable=/usr/local/bin/wireguard-ui

[Service]  
Type=simple 
 ExecStart=/usr/local/bin/wireguard-ui 
Restart=on-failure 
SyslogIdentifier=wireguard-ui                                                                                           Environment="WGUI_DEFAULT_CLIENT_ALLOWED_IPS=10.0.0.0/24"                                                               Environment="SMTP_HOSTNAME=mail.fy.cz"
 Environment="SMTP_PORT=587"
Environment="SMTP_AUTH_TYPE=none"                                                                                       Environment="EMAIL_FROM_ADDRESS=helpdesk@bbbb.cz"                                                                   Environment="EMAIL_FROM_NAME=WireguardVPN"

**Comment by holotrack** [comment]
Same for me, environment variables are not taken into account

**Comment by kprose3154** [comment]
I'm running mine using Docker Compose and noticed if you make changes to env variables it will not take it into account. The solution I found is to delete the db folder or modify the files inside if you already setup the instance.
