### ISSUE TITLE
After Newclient, you need to wg-quick restart on the server

### ISSUE THREAD

**Issue by miffyrcee** [ngoduykhanh/wireguard-ui#254]
When I use wg-ui to add a client, I must use wg-quick down wg0; wg-quick up wg0, it will take effect in wg-qucik. Is there a way to solve this on the front end, avoiding the need for someone else to log into the server.

**Comment by miffyrcee** [comment]
Wireguard UI
App Version     : v0.3.7
Git Commit      : ad4ca4d9bb344236a2793fee54ec24cf07d6cd8c
Git Ref         : refs/tags/v0.3.7
Build Time      : 11-09-2022 17:09:18

**Comment by holotrack** [comment]
@miffyrcee did you created needed systemd services like described on readme page?

**Comment by miffyrcee** [comment]
Ok，Thanks。I'm missing a systemd configuration for PATH listening
