### ISSUE TITLE
Existing peers and keys migration from original Wireguard

### ISSUE THREAD

**Issue by andyi95** [ngoduykhanh/wireguard-ui#255]
Hi to all!
I'm having an existing Wireguard instance, using [linuxserver/wireguard](https://hub.docker.com/r/linuxserver/wireguard) Docker image. It works well, but having a bit different config structure from this implementation. I couldn't find any way to migrate existing peers and keys to Wireguard-ui from the original one. 
As I can see, the current implementation keeps both server and client keys in one `wg0.conf`, plus using a sort of DB, which is a set of JSON files with the same server peer keys as in config with some added parameters. In my opinion, it's not the best way of managing peers' keys as we have two sources of truth and two points of possible attack. But the most important, it's pretty hard to manage all that manually.
Would it be possible to implement auto-import existing configs if they are in mounted catalogs or, at least, some reliable way to migrate them manually? Maybe it's possible to auto-generate wg0.conf from the set of manually created json files?

**Comment by Niek** [comment]
See: https://github.com/ngoduykhanh/wireguard-ui/issues/135
