### ISSUE TITLE
QR-code not working

### ISSUE THREAD

**Issue by Snickser** [ngoduykhanh/wireguard-ui#257]
QR-code generate button is disabled
image from docker hub - ngoduykhanh/wireguard-ui:latest and 0.3.7

![изображение](https://user-images.githubusercontent.com/88129688/202653420-7c9c64de-c79a-4cdc-81dc-3e9764a83aa6.png)

**Comment by Snickser** [comment]
it's because the field "privkey" in profile's is empty... ;)

**Comment by ngoduykhanh** [comment]
The document or UI needs to be adjusted to warn the user :)

**Comment by babblo** [comment]
Which private_key field?
