### ISSUE TITLE
Incorrect URL on logout - prevents logging back in

### ISSUE THREAD

**Issue by pobouchard** [ngoduykhanh/wireguard-ui#259]
Hi,

On initial access to the server, the login page is shown with this url:
http://my-server-fqdn:5000/login?next=/
Admin logs in, applies changes, etc, then logs out.

On log out the browser is sent to this URL:
http://my-server-fqdn:5000/login (missing the ?next=/ part).
Attempting to log in from there sends the browser to: http://my-server-fqdn:5000/wireguard which fails.

It looks like the logic adding "?next=/" to the URL on initial connection may need to be added to the logout process?
Docker config has BASE_PATH=/ though I stumbled upon this without setting BASE_PATH as well.

Thanks!

**Comment by systemcrash** [comment]
Problem is here

https://github.com/ngoduykhanh/wireguard-ui/blob/be2ffba4176cdee99e46be79ceb7afe075a6195f/templates/login.html#L88

Should be modified to handle either `/` or add the `BASE_PATH`
