### ISSUE TITLE
My working FreeBSD startup scripts

### ISSUE THREAD

**Issue by krolingo** [ngoduykhanh/wireguard-ui#264]
For anyone interested, here are my scripts to get this working properly on FreeBSD:

**1. wireguard-ui daemon:  /usr/local/etc/rc.d/wireguard-ui**

```
#!/bin/sh
#
# PROVIDE: wireguard_ui
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable wireguard_ui:
#
# wireguard_ui_enable="YES"
#

. /etc/rc.subr
name="wireguard_ui"
rcvar=wireguard_ui_enable
procname="/usr/local/opt/wireguard-ui/wireguard-ui"
pidfile="/var/run/wireguard_ui.pid"
wireguard_ui_chdir="/usr/local/opt/wireguard-ui"
wireguard_ui_env_file="/usr/local/opt/wireguard-ui/env"

command="/usr/sbin/daemon"
command_args=" -s notice -p ${pidfile} -f ${procname} ${wireguard_ui_env_file}"

stop_postcmd="wireguard_ui_poststop"

wireguard_ui_poststop()
{
    rm -f $pidfile
}

load_rc_config ${name}

: ${wireguard_ui_enable="NO"}
: ${wireguard_ui_pidfile="/var/run/${name}.pid"}

run_rc_command "$1"
```

**2. daemon to watch for changes made by wireguard-ui then restart wireguard to commit the changes**

```
#!/bin/sh
#
# PROVIDE: wgui
# REQUIRE: DAEMON
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable wgui:
#
# wgui_enable="YES"
#

. /etc/rc.subr

name="wgui"
rcvar=wgui_enable
procname="/usr/local/opt/wgui/wgui"
pidfile="/var/run/wgui.pid"
#wgui_chdir="/usr/local/opt/wgui/"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} ${procname}"

stop_cmd="${name}_stop"
stop_postcmd="${name}_poststop"


wgui_stop()
{
        if [ -f $pidfile ]; then
                echo "Stopping wgui."
                kill $(cat $pidfile)
                echo "Stopped wgui."
        else
                echo "wgui is not running."
                exit 0
        fi
}


wgui_poststop()
{
        rm -f  $pidfile
}

load_rc_config ${name}

: ${wgui_enable="NO"}
: ${wgui_pidfile="/var/run/${name}.pid"}

run_rc_command "$1"
```

**3. script for the daemon:**

```
#!/bin/sh
PATH="$PATH:/usr/local/bin"
while inotifywait -e modify -e create  /usr/local/etc/wireguard/; do
  wg-quick down wg0
  wg-quick up wg0
done
```

Caveat: For the wgui script to work you will need to install inotify-tools first.
`# pkg install inotify-tools`

**Comment by joeldahl** [comment]
Maybe submit this to the FreeBSD ports collection?

**Comment by esmoyer** [comment]
Got got this all setup, and try to start the service, but even though it says it's starting when I try service wireguard-ui status, it says it's not running. Can't seem to figure out what I missed, would you happen to have any insight?

**Comment by krolingo** [comment]
> Got got this all setup, and try to start the service, but even though it says it's starting when I try service wireguard-ui status, it says it's not running. Can't seem to figure out what I missed, would you happen to have any insight?
> 
> EDIT: Got it running, but the only thing I can't seem to figure out is how to get the peers/clients to be seen by OPNsense, but maybe that isn't possible?

did you get the "connected peers" feature working?
