### ISSUE TITLE
Default username and password currently do not work

### ISSUE THREAD

**Issue by systemcrash** [ngoduykhanh/wireguard-ui#269]
Omitting `WGUI_USERNAME` and `WGUI_PASSWORD` at `docker-compose` kickstart does not revert to `admin`/`admin`. 

Tested on be2ffba4176cdee99e46be79ceb7afe075a6195f

**Comment by AndreyKusko** [comment]
whatch out docker-compose config. there are different settings

**Comment by MrAkells** [comment]
I confirm. I used binaries and these variables are ignored.

**Comment by ngoduykhanh** [comment]
The current implementation of this environment variable only works on a new DB initialization. It doesn't override the existing user information if the user DB exists. We might want to change this 🤔

**Comment by gnat** [comment]
Please! There really should be a way to change the username/password after installation. Environment variable, parameter, or in the UI- any of these would be okay.

Also would be nice to have a login delay well to help prevent brute forcing of the password- currently `wireguard-ui` requires either a very long password or a firewall in front. :eyes:

**Comment by ngoduykhanh** [comment]
I added a feature to update the user profile via UI. Please check it out in the latest docker build or master branch.

**Comment by gnat** [comment]
@ngoduykhanh Thank you! Could we get a new tag/release on Github?
