### ISSUE TITLE
latest-arm64 docker image is built for amd64

### ISSUE THREAD

**Issue by fasmat** [ngoduykhanh/wireguard-ui#273]
I just tried to run Wireguard UI on my raspberry pi and failed to do so, because I'm getting "exec format error" when I start a container from the image.

This must have broken recently, because I know it worked about a month ago without any issues. `docker-compose logs`:

```
$ docker compose logs -f
wgui  | exec ./init.sh: exec format error
wgui  | exec ./init.sh: exec format error
```

Update: changing the entrypoint of the service in `docker-compose.yml` to `entrypoint: ["./wg-ui"]` fixes the issue:

```
$ docker compose logs -f
wgui  | Wireguard UI
wgui  | App Version	: development
wgui  | Git Commit	: N/A
wgui  | Git Ref		: N/A
wgui  | Build Time	: 12-16-2022 10:34:58
wgui  | Git Repo	: https://github.com/ngoduykhanh/wireguard-ui
wgui  | Authentication	: true
wgui  | Bind address	: 0.0.0.0:8080
wgui  | Email from	: 
wgui  | Email from name	: WireGuard UI
wgui  | Custom wg.conf	: 
wgui  | Base path	: /
wgui  | ⇨ http server started on [::]:8080
```

**Comment by ngoduykhanh** [comment]
Updated the tag. It should work now. Thanks for reporting 👍
