### ISSUE TITLE
When changing to Use Server DNS or not the QR code is not updated.

### ISSUE THREAD

**Issue by jpdsc** [ngoduykhanh/wireguard-ui#275]
When generating a peer with `Use Server DNS` checked generates a config and QR with DNS settings.
However, if editing the user and removing `Use Server DNS`; the config is updated but the QR code isn't for the DNS settings. It should remove them.
Allowed IPs is updated in the QR.

**Comment by ngoduykhanh** [comment]
Closing in favor of linked PR.
