### ISSUE TITLE
SSL or configurable bind address

### ISSUE THREAD

**Issue by drequivalent** [ngoduykhanh/wireguard-ui#29]
It's more than a little adventurous to configure VPN via HTTP with no encryption.
Why don't we either 
a) support SSL options
or
b) support binding to the localhost so that the panel can be ssl-terminated

**Comment by ngoduykhanh** [comment]
I prefer the option `b`. Will do to have the address binding setting.

**Comment by ngoduykhanh** [comment]
Address binding supported in #36
