### ISSUE TITLE
Cannot apply server config Ubuntu x64

### ISSUE THREAD

**Issue by francisuk1989** [ngoduykhanh/wireguard-ui#304]
Hello.

When apply config, i get the error

`Cannot apply server config: open /etc/wireguard/wg0.conf: no such file or directory`

Ubuntu 22.10 x64
```
App Version	: v0.4.0
Git Commit	: be2ffba4176cdee99e46be79ceb7afe075a6195f
Git Ref		: refs/tags/v0.4.0
Build Time	: 01-19-2023 10:26:16
```

**Comment by bitdruid** [comment]
> Hello.
> 
> When apply config, i get the error
> 
> `Cannot apply server config: open /etc/wireguard/wg0.conf: no such file or directory`
> 
> Ubuntu 22.10 x64
> 
> ```
> App Version	: v0.4.0
> Git Commit	: be2ffba4176cdee99e46be79ceb7afe075a6195f
> Git Ref		: refs/tags/v0.4.0
> Build Time	: 01-19-2023 10:26:16
> ```

try `sudo touch /etc/wireguard/wg0.conf` and check again if you can apply your settings
