### ISSUE TITLE
[FEAT] env to change web-ui default port 5000 // set disable_login

### ISSUE THREAD

**Issue by bitdruid** [ngoduykhanh/wireguard-ui#305]
would love to set a custom port which the ui is listening on via ENV as it would provide a better port management with a lot of running container (to set port numbers incremental for all containers)

further i really liked to set --disable-login on my old setup. now with docker it seems that i can't disable login anymore or did i miss something? maybe this would also be a good feature for an ENV

**Comment by ByteDream** [comment]
> would love to set a custom port which the ui is listening on via ENV as it would provide a better port management with a lot of running container (to set port numbers incremental for all containers)

This is already implemented but undocumented at is seems. You can use the `BIND_ADDRESS` env variable to set the port. It must be formatted as `<address>:<port>`. For example `BIND_ADDRESS=0.0.0.0:4000` would listen on port 4000.

> further i really liked to set --disable-login on my old setup. now with docker it seems that i can't disable login anymore or did i miss something? maybe this would also be a good feature for an ENV

This is also implemented but not documented. Set the `DISABLE_LOGIN` env variable to `true` and it behaves the same as `--disable-login` would.
