### ISSUE TITLE
problem with wireguard-ui on Herzner VPS

### ISSUE THREAD

**Issue by otolghoraze** [ngoduykhanh/wireguard-ui#312]
Hi everyone,
I buy a VPS from the Hetzner data center and install the Wireguard-ui APP from the Hetzner panel. In the first boot, the server asked me about my domain, password, and email address to set up the Wireguard-ui, and everything goes normal. After finishing the installation, the server announced me to open my domain. So, everything was OK on the domain and I entered my user and password and created a new client. The problem is, none of my clients can access the internet. Although everything seems right, I don't have any internet access from my smartphone or PC! I'm not a professional in Linux and I can't understand what is going on! I will be very appreciative If you have any experience with this issue to help me or if you know how to resolve the problem.
Thanks.

**Comment by libracoder** [comment]
How did you solve this, I have thesame issue

**Comment by blazesysadmin** [comment]
> > The problem is, none of my clients can access the internet. Although everything seems right, I don't have any internet access from my smartphone or PC!
> 
> Hi.
> 
> Have you tried clicking the "apply config" button after adding new clients?



This "Apply Config" is the right fix and works for me. Thanks!

**Comment by adnan-smlatic** [comment]
> > The problem is, none of my clients can access the internet. Although everything seems right, I don't have any internet access from my smartphone or PC!
> 
> Hi.
> 
> Have you tried clicking the "apply config" button after adding new clients?

Oh my god, thank you, I spent hours debugging just to find out I didn't click the fucking button
