### ISSUE TITLE
[Feature request] Endpoint as an Optional field

### ISSUE THREAD

**Issue by ssnfcmux** [ngoduykhanh/wireguard-ui#313]
For now I'm forced to use "Persistent Keepalive" to keep an SSH connection constant with my (( Servers )) ...

As I know >> it's possible to tell Wireguard where to find a specific client by providing the client's public IP, which Wireguard calls the "Endpoint" field.

Is it possible to add this field to the UI, and make it optional?

**Comment by rookie50** [comment]
that would be great. I want to run a site-to-site VPN and client on one wireguard instance. When I add an addition VPN client, the site-to-site will be overwritten.
