### ISSUE TITLE
wireguard-ui STATUS

### ISSUE THREAD

**Issue by SimonasBitai** [ngoduykhanh/wireguard-ui#317]
Hello,
I have wireguard in one container and in other wireguard-ui container on ubuntu 22. Everything works fine except STATUS. It is possible to do STATUS working when they are in different containers ?

**Comment by bitdruid** [comment]
unfortunately not. this is why i installed wireguard directly on the host. but there are projects which integrate wg and the ui in one container

**Comment by SimonasBitai** [comment]
After few weeks of research and tests with colleague we did it :) Both containers running on Network_mode: host and everything wokrs fine ant STATUS also :)

**Comment by agrol1** [comment]
I found a solution to this to run on my own docker network
The thing to do is on the wireguard ui container to use `network_mode: service:vpn` so when it runs wg commands it is in the same container as the wireguard service is running 

See my docker-compose below sorry for the bad formatting I don't know how to get it ok in this page 


> version: "2.1"
networks:
  traefik:
    external: true
services:
  vpn:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - ALLOWEDIPS=0.0.0.0/0
      - PEERS=1
      - SERVERPORT=51820
      - SERVERURL=yourdomain.com
      - INTERNAL_SUBNET=192.168.100.0
      - PEERDNS=1.1.1.1 
    volumes:
      - /docker/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
      - 5000:5000
    restart: unless-stopped
  vpn-ui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wg-ui
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      - SESSION_SECRET=TopSECRET
      - WGUI_USERNAME=USER
      - WGUI_PASSWORD=SECRET
      - WGUI_MANAGE_START=false
      - WGUI_MANAGE_RESTART=true
      - WGUI_ENDPOINT_ADDRESS=yourdomain.com
      - WGUI_DNS=1.1.1.1
      - WGUI_PERSISTENT_KEEPALIVE=25
      - WGUI_SERVER_INTERFACE_ADDRESSES=192.168.100.1/24
     logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - /docker/wg-ui:/app/db
      - /docker/wireguard:/etc/wireguard
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
