### ISSUE TITLE
Client IP Allocation - change default subnet mask

### ISSUE THREAD

**Issue by Eagle6705** [ngoduykhanh/wireguard-ui#319]
I can't find the default values for the client IP allocation.  I want to set it so clients get a /24 instead of /32

Ie Client1 gets 10.0.1.1/24 instead of the default 10.0.1.1/32

**Comment by systemcrash** [comment]
Specify it yourself under Alllowed IPs. You can widen to a /24

Check code for `ValidateIPAllocation`
