### ISSUE TITLE
[BUG] wireguard-ui docker can't resolve HEALTHCHECK if BASE_PATH is set

### ISSUE THREAD

**Issue by bitdruid** [ngoduykhanh/wireguard-ui#320]
- expose port 5000 with network_mode: host
- BASE_PATH=/stuff/wireguard-ui/

**actual behaviour:**
- healthcheck cant find wg-ui - switches status to unhealthy:
id= remote_ip=127.0.0.1 host=127.0.0.1:5000 method=GET uri=/_health user_agent=Wget status=404 error=code=404, message=Not Found latency=97222 latency_human=97.222µs bytes_in=0 bytes_out=24

**expected behaviour:**
- healthcheck succeeds:
id= remote_ip=127.0.0.1 host=127.0.0.1:5000 method=GET uri=/_health user_agent=Wget status=200 error= latency=242260 latency_human=242.26µs bytes_in=0 bytes_out=2

I think host should get BASE_PATH var

**Comment by systemcrash** [comment]
What is it that you think `BASE_PATH` does?

**Comment by bitdruid** [comment]
> What is it that you think `BASE_PATH` does?

handles my subpath behind reverse-proxy. or what do you mean? if i dont set the base_path i can't reach wireguard-ui with my current setup - have to connect via ip:port

**Comment by systemcrash** [comment]
Ah - looked like you maybe thought it was file path. We could do with disambiguating this variable. Did you try without trailing `/`?

**Comment by bitdruid** [comment]
> Ah - looked like you maybe thought it was file path. We could do with disambiguating this variable. Did you try without trailing `/`?

Just an explanation:
When `BASE_PATH `is set, i can reach my services either with `<ip>:<port>/subdir/wireguard-ui/` or with `example.org/subdir/wireguard-ui/`

as without `BASE_PATH `the healthceck uses `GET `on `<ip>:<port>` i came to the conclusion, that it must include the path there. Just my thoughts. Until now i had not the need to build an image and so i have no idea how the healthcheck exactly works.

But back to your tip:
I removed the trailing slash but the response keeps the same.

**Comment by systemcrash** [comment]
OK - pretty sure the problem is in the `Docker` file which has:

`HEALTHCHECK CMD ["wget","--output-document=-","--quiet","--tries=1","http://127.0.0.1:5000/_health"]`

It could be extended to add a docker ENV variable, namely BASE_PATH. That BASE_PATH gets baked in at compile time, but can change at run time. Not sure how to reconcile those, such that one could get away with e.g.:

`HEALTHCHECK CMD ["wget","--output-document=-","--quiet","--tries=1","http://127.0.0.1:5000/$BASE_PATH_health"]`

**Comment by Inosss** [comment]
bump
