### ISSUE TITLE
Build container and push to GHCR

### ISSUE THREAD

**Issue by porjo** [ngoduykhanh/wireguard-ui#327]
It would be great if a container were built and pushed into GHCR (Github container registry) upon each release.

Here is an example Github workflow that could be used as a template: https://github.com/porjo/ytdl-web/blob/master/.github/workflows/build-and-push.yml . The only thing that should need changing is to replace:

```
on:
  push:
    tags:
      - "*"
```
with
```
on:
  release:
    types: [created]
```

The repository owner would first need to create a PAT with permissions ` repo, workflow, write:packages` and add it to the repository's secrets.

**Comment by ByteDream** [comment]
I think this gets more relevant as docker hub plans to [shut down the organizations free tier](https://blog.alexellis.io/docker-is-deleting-open-source-images/). This does not impact the docker image of this repo as it's published via a personal account but some (more) people might prefer GHCR over docker hub after this decision.

**Comment by porjo** [comment]
I actually didn't realise it was available on Dockerhub! (no mention in the README). I'm happy to go with that.
