### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by JanLp** [ngoduykhanh/wireguard-ui#329]
Please use the timezone specified in docker-compose.yaml

`TZ=Europe/Copenhagen`

![Skærmbillede 2023-02-19 kl  13 08 30](https://user-images.githubusercontent.com/55313117/219947008-8ce5895e-d34f-4bcf-a975-9f11fb0017b7.png)

**Comment by agrol1** [comment]
Hi 
I just found an alternative solution

remove 
environment:
      - TZ=Europe/Stockholm 
 
add 
volumes:
      - /etc/localtime:/etc/localtime:ro

After the clients first connection the time is shown in your hosts timezone 

![Screenshot 2023-02-21 21 43 39](https://user-images.githubusercontent.com/86733700/220454504-dda008cc-ff21-40d9-bb3e-d8c8fd5f732d.png)

**Comment by JanLp** [comment]
Thank you 🙏

**Comment by romprod** [comment]
I had the same issue but couldn't get this to work because the image is missing the tzdata package.

I didn't need to map the additional volume but I did need a Dockerfile with the following

`FROM ngoduykhanh/wireguard-ui:latest

RUN apk update && apk add tzdata`
