### ISSUE TITLE
WOL does not work in bridge networks mode

### ISSUE THREAD

**Issue by krisraich** [ngoduykhanh/wireguard-ui#333]
Hello

It seems to appear, that WOL does not work, when this contianer is connected via bridge networks.
I use a reverse proxy, to access the ui.

Is there a workaround for this issue?

**Comment by Nomis1981** [comment]
Hi,
maybe it's possible to make a second field for a static-ip adress, like it does this program:

https://www.boc.de/watchguard-info-portal/2020/03/howto-wake-on-lan-via-vpn-verwenden/

Would be really nice, then i could do all in one program :)
