### ISSUE TITLE
Server interface address seems awkward

### ISSUE THREAD

**Issue by olaf7** [ngoduykhanh/wireguard-ui#336]
The default value for WGUI_SERVER_INTERFACE_ADDRESSES is currently 10.252.1.0/24
With that value the wg0 interface on the server becomes 10.252.1.0 which prevents clients from SSHing into the server. As .0 is a reserved value in IPv4 address subnets services such as OpenSSH might not like it. Changing this to .1 fixes this.

**Comment by nick-george** [comment]
I'm a new user of this project, just came across this issue myself.
