### ISSUE TITLE
Can I run it just as a UI with my existing wireguard installation?

### ISSUE THREAD

**Issue by jimaldon** [ngoduykhanh/wireguard-ui#340]
Looking for plain UI and interfacing functionality with my existing wireguard installation running in a docker container. Like how [wg-ui](https://github.com/EmbarkStudios/wg-ui) does it

**Comment by ByteDream** [comment]
[docker-compose.yaml](https://github.com/ngoduykhanh/wireguard-ui/blob/master/docker-compose.yaml) should handle that.

**Comment by jimaldon** [comment]
it looks like docker-compose.yml starts it's own wireguard server (according to init.sh)On Mar 13, 2023, at 17:48, ByteDream ***@***.***> wrote:﻿
docker-compose.yaml should handle that.

**Comment by ByteDream** [comment]
What the init script does depends on the environment variables. `WGUI_MANAGE_START` can start and `WGUI_MANAGE_RESTART` can restart the wireguard interface. If you do not want these functionalities, simply set this variables to `false`. But at least `WGUI_MANAGE_RESTART` should be set as the wireguard interface needs to be restarted when the configuration changes (e.g. new clients are added).
