### ISSUE TITLE
Existing wireguard configuration is not fetched on first start

### ISSUE THREAD

**Issue by diggy128** [ngoduykhanh/wireguard-ui#348]
When running wireguard-ui for the first time any existing configuration in wg0.conf is not fetched.
That is clients, server settings and global settings.
Status shows the currently active clients though

**Comment by YueyuHoshizora** [comment]
I'm also having the same problem, and I'm a bit stuck right now.

**Comment by diggy128** [comment]
Skimming through the code I didn't find any function that imports the current conf. It seems to only generate a new conf each time from the records in its own db.

As I was in a bit of a hurry and only had ~10 clients, I just created "dummy" entries and copy-pasted the keys from the previous conf.

**Comment by YueyuHoshizora** [comment]
@diggy128 
May I ask where is the program you found? I may be able to assist in fixing this.

**Comment by diggy128** [comment]
I didn't use any extra program. I just edited the information that was stored in the database.

**Comment by yodaphone** [comment]
AFAIK you cannot import any existing configuration into wireguard-ui

**Comment by diggy128** [comment]
@yodaphone OK, maybe it could be in the documentation or github page to save other people some time trying to find out why it doesn't work with existing configurations.

**Comment by mad-ady** [comment]
Yup, I'm affected as well. Saving the server configuration nukes the original config... 
This would mean that it doesn't allow users to make manual changes to the wireguard server config, and it always overwrites that config with whatever it has in its database. Might cause issues down the road...

**Comment by madtempest** [comment]
It's especially an issue when using something like the LinuxServer prebuilt container unless the intent is that you leave that blank and make the wireguard LS container depend on the wireguard-ui container to ensure that wg0.conf is autogenerated.

As it stands now though, I am not seeing the private key etc in wireguard-ui being pushed into an existing wg0.conf generated by LS which might be permissions or something else, I don't know. Clearer docs would be awesome, as would an import function.

**Comment by PlexSheep** [comment]
I have the same problem. It took me a lot of time to make a working vpn configuration manually, usage of this ui tool overwrites my (backupped) configs. Creating a new client also does not build a working config file for me.

**Comment by mad-ady** [comment]
Well, this is odd. I thought of giving this project a second chance on a new wireguard setup. I used the UI from start to finish to set up the wireguard configuration. I did change the suggested tunnel address, and proceeded with the configuration. When i was done, I applied, checked that the config files were ok (I used wg0 as interface), and stopped the wireguard-ui application. Next, I moved the binary to /usr/local/bin, created a systemd startup script for it and started it via systemd. Well - surprise - it started, but it didn't load the configuration. It behaved as if wg0 was not configured by it and didn't import anything. 

I suspect it's keeping a cache of settings somewhere and can't find it when started through systemd...

**Comment by mad-ady** [comment]
Update: Figured it out with a bit of `strace` trickery: The application creates and maintains its database in a `db` directory relative to the current working directory from where it was started. I moved the db directory into /etc/wireguard, and instructed the systemd service to load it from there:

```
[Unit]
Description=Starts wireguard-ui
After=network.service

[Service]
Type=simple
User=root
WorkingDirectory=/etc/wireguard
ExecStart=/usr/local/bin/wireguard-ui
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```
