### ISSUE TITLE
email not going

### ISSUE THREAD

**Issue by Forsskieken** [ngoduykhanh/wireguard-ui#351]
Hi there,

I'm guessing the settings for google gmail in /etc/envirionment but it's not working
I looked in the source code and guesed this:
  GNU nano 5.4                                                          /etc/environment                                                                    
hostname=smtp.gmail.com
port=587
username=this.emailadress@gmail.com
password=vlqsolltfknmwfcd  #generated app passwd
authType=PLAIN
encryption=TLS
noTLSCeck=no
fromName="This Email"
from="this.emailadress@gmail.com"

Can you point me to my mistake?
I always seem to get this error:
Mail Error on dialing with encryption type STARTTLS: dial tcp 127.0.0.1:25: connect: connection refused

**Comment by Forsskieken** [comment]
So what I do:
make changes to /etc/environment
systemctl stop wireguard-ui
cd /opt/wireguard
./wireguard-ui
This is the error now....
530 5.7.0 Authentication Required. Learn more at 5.7.0 https://support.google.com/mail/?p=WantAuthError i22-20020a05600c355600b003ede6540190sm11299741wmq.0 - gsmtp

**Comment by yodaphone** [comment]
can you make sure you are using the app password instead of the regular password with 2FA?

**Comment by Forsskieken** [comment]
I have in /etc/enviornment
SMTP_ENCRYPTION=STARTTLS
SMTP_HOSTNAME=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=My.email@gmail.com
SMTP_PASSWORD=qenpnpydfddfghp
SMTP_AUTH_TYPE=LOGIN
EMAIL_FROM_ADDRESS=My.email@gmail.com
EMAIL_FROM_NAME=Wireguard Ui

cd /opt/wireguard-ui 
./wireguard-ui systemctl start wireguard-ui
Now I can mail but if I restart the container I have to apply the two line above why?

**Comment by Dr4tez** [comment]
> I have in /etc/enviornment SMTP_ENCRYPTION=STARTTLS SMTP_HOSTNAME=smtp.gmail.com SMTP_PORT=587 SMTP_USERNAME=[My.email@gmail.com](mailto:My.email@gmail.com) SMTP_PASSWORD=qenpnpydfddfghp SMTP_AUTH_TYPE=LOGIN EMAIL_FROM_ADDRESS=[My.email@gmail.com](mailto:My.email@gmail.com) EMAIL_FROM_NAME=Wireguard Ui
> 
> cd /opt/wireguard-ui ./wireguard-ui systemctl start wireguard-ui Now I can mail but if I restart the container I have to apply the two line above why?

I don't know how it works with containers, because I'm using a binary file, and in my case I added a task to the cron to start wireguard-ui at system startup and it works::
`crontab -e`
add line
**@reboot ./wireguard-ui**
save and reboot the system.
