### ISSUE TITLE
How to regenerate wg0.conf from DB

### ISSUE THREAD

**Issue by kornpow** [ngoduykhanh/wireguard-ui#354]
I know this might not be the intended usage of this tool, but I would like to be able to create a new file in `/db/clients/x.json` and be able to restart wireguard-ui and have it be added to wg0.conf.

For some reason I have created the file and restarted `wireguard-ui`, it doesnt update `wg0.conf`. If I delete `wg0.conf`, and then restart `wireguard-ui`, it will regenerate the file with the new client.

Can you help me with this use case?

**Comment by kornpow** [comment]
I also do not really understand the naming convention for the `id`? `cg4d6mr0sq8auot174ig` From attempting to look at the code, it appears to be some kind of hash, but I cannt tell if it MUST be a hash, or it could be anything.

**Comment by Loxbie** [comment]
If I understand you correctly you are trying to edit the client db and want this to be reflected in the `wg0.conf` file?

Try this:

- start wireguard-ui
- copy or create a new `.json` in `db/clients/`,
- browse to "Wireguard Clients" in wireguard-ui and refresh the site 
- click "Apply Config"

This should then create a corresponding entry in your `wg0.conf`. I tested it with this client file `thisisaclientid.json`:

```json
{
        "id": "thisisaclientid",
        "private_key": "yourkeyhere",
        "public_key": "yourpublickeyhere",
        "preshared_key": "yourkeyhere",
        "name": "your_new_client_id",
        "email": "something@your-domain.com",
        "allocated_ips": [
                "10.252.1.1/32"
        ],
        "allowed_ips": [
                "100.64.105.12/32"
        ],
        "extra_allowed_ips": [],
        "use_server_dns": true,
        "enabled": true,
        "created_at": "2023-05-08T12:14:18.813915466Z",
        "updated_at": "2023-05-08T12:14:18.813915466Z"
}
```

Which creates this `wg0.conf` for me:

```bash
# ID:           thisisaclientid
# Name:         your_new_client_id
# Email:        something@your-domain.com
# Created at:   2023-05-08 12:14:18.813915466 +0000 UTC
# Update at:    2023-05-08 12:14:18.813915466 +0000 UTC
[Peer]
PublicKey = yourpublickeyhere
PresharedKey = yourkeyhere
AllowedIPs = 10.252.1.1/32
```

Please be aware that I am **unsure** if this is working as intended and that those changes might break stuff!
