### ISSUE TITLE
Docker Compose Linux Server Not Working

### ISSUE THREAD

**Issue by itsMikeLowrey** [ngoduykhanh/wireguard-ui#360]
Hi. When I use the docker instructions for linuxserver, found here https://github.com/ngoduykhanh/wireguard-ui/blob/master/examples/docker-compose/linuxserver.yml, the GUI server starts up and runs but when I add clients they do not have internet access. I have wireguard installed and wg gives me no errors. I see logs in the terminal but there are no errors, just updates when I had clients etc. How should I go about debugging the clients not having internet access issue?

I also only get this issue: 
Warning: `/etc/wireguard/wg0.conf' is world accessible
Edit:
The GUI lags when I try to load it and I get this error:
{"time":"2023-04-12T04:00:12.332389874Z","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:5000","method":"GET","uri":"/_health","user_agent":"Wget","status":200,"error":"","latency":72907,"latency_human":"72.907µs","bytes_in":0,"bytes_out":2}

**Comment by Inosss** [comment]
add this environments to docker-compose.yml for wireguard-ui:

      - WGUI_SERVER_POST_UP_SCRIPT=iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
      - WGUI_SERVER_POST_DOWN_SCRIPT=iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
      
and this to wireguard envs:
      - PEERS=1


In my case wireguard starts in client mode, peers=1 resolves it. And than i have problem with post up/down scripts is empty. We can fix it by envs.

**Comment by itsMikeLowrey** [comment]
Thank you so much for the help.
