### ISSUE TITLE
what port to use for UI?

### ISSUE THREAD

**Issue by hemna** [ngoduykhanh/wireguard-ui#366]
Hello,
 I am using the docker compose for linuxserver and the definition for the wireguard-ui doesn't list a port to expose the UI for http requests.  What port settings should be used?

**Comment by ByteDream** [comment]
Should be 5000

https://github.com/ngoduykhanh/wireguard-ui/blob/ac99317ba3ff35eb169b6acc561ecf6f674f4062/examples/docker-compose/linuxserver.yml#L12-L13

**Comment by operationairstrike** [comment]
Same
