### ISSUE TITLE
User settings after system restart or container restart

### ISSUE THREAD

**Issue by rtmlp** [ngoduykhanh/wireguard-ui#368]
Hi,

I have the wireguard setup with the linuxserver wireguard. I have couple of questions

 **Scenario 1**:  I am connected to VPN on my phone using wireguard client. After some time, I restart the containers with `docker-compose down` and `docker-compose up -d`. What happens to the VPN connection on my phone. Will it be disconnected temporarily until the connection is restored or do I have re-download the `.conf` file or use the `QR code` to setup the connection again ?
 
 **Scenario 2** Similar to scenario 1.  If I restart the host system and set up a startup script to run the compose file, do I have make any changes on the client (updating connection etc) after the host system restarts. 

I guess both of the scenarios are centered around the question of 
- will the user settings be preserved during container or system restarts ?

**Comment by archef2000** [comment]
**Scenario 1**: The client should reconnect on its own
**Scenario 2**: You should set `restart: unless-stopped` to both services inside the compose file so they start up when the docker deamon is starting on system boot without further config
