### ISSUE TITLE
Proxy subpath handling

### ISSUE THREAD

**Issue by tituspijean** [ngoduykhanh/wireguard-ui#37]
The webapp does not handle being proxified to a subpath, as all routes expect to be ran from the root of the domain.

Running `./wireguard-ui --bind-address="127.0.0.1:8097" --disable-login`, with the following Nginx config so that the webapp is available on `domain.tld/wireguard/`:

```
 rewrite ^/wireguard$ /wireguard/ permanent;
location /wireguard/ {

  # Force usage of https
  if ($scheme = http) {
    rewrite ^ https://$server_name$request_uri? permanent;
  }

  proxy_pass        http://127.0.0.1:8097/;
  proxy_redirect    off;
  proxy_set_header  Host $host;
  proxy_set_header  X-Real-IP $remote_addr;
  proxy_set_header  X-Forwarded-Proto $scheme;
  proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header  X-Forwarded-Host $server_name;
  proxy_set_header  X-Forwarded-Port $server_port;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
}
```

For example, clicking on the `Wireguard Server` menu will link to `https://domain.tld/wg-server` instead of `https://domain.tld/wireguard/wg-server`.

**Comment by ngoduykhanh** [comment]
The HTML relative links seem incorrect in this scenario, let me find a solution for this.

**Comment by dsvf** [comment]
+1
Use case: using apache as HTTPS proxy and auth, forwarding https://example.com/wireguard to http://localhost:5000.
So far, I was unable to get it to completely work, apaches rewrite magic fails when adding clients.

Being able to tell wireguard-ui that it is served from some other webroot(?) than / would be helpful

**Comment by Apollo3zehn** [comment]
This would be a great addition as I have the same problem. All my internal services run on http://IP:8080/service-name and the wireguard-UI fails to properly work with that setup.

My nginx configuration is quite simple:

```conf
server {
    listen 8080;

    location /wireguard/ {
        proxy_pass http://127.0.0.1:8009/;
    }
}
```

I know I need to add the X-Forwarded headers but tituspijean has already shown that these are getting ignored. A simple solution would be to parse the HTTP frame X-Forwarded header information and use it to build the correct base path.

**Comment by bitdruid** [comment]
i fully agree with that. it would be a really nice feature. i even cant login when wgui is reverse proxied to a subfolder. however a little woraround for now is using subdomains...

**Comment by elcajon** [comment]
I stumbled across this problem today. Is there a plan to add this feature?

**Comment by lkohari** [comment]
Hi,
Is there anyone found the solution for this issue? I try to set up an apache2 proxy to make the webui work, but no luck.

I tried several different config, this is the last one:
ProxyPass /wgui/ http://127.0.0.1:5000/
<Location /wgui/>
    ProxyPreserveHost On
    ProxyPassReverse /
    ProxyPassReverseCookiePath / /wgui/
    RewriteEngine On
    RewriteRule ^/wgui$ /wgui/ [R]

    # Set headers
    RequestHeader set Host $host
    RequestHeader set X-Real-IP $remote_addr
    RequestHeader set X-Forwarded-Proto $scheme
    RequestHeader set X-Forwarded-For $proxy_add_x_forwarded_for
    RequestHeader set X-Forwarded-Host $server_name
    RequestHeader set X-Forwarded-Port $server_port
</Location>

The goal is that my webserver is serving many different things like cups, pihole, transmission webui, and every time I just create an apache reverse proxy, and don't open the firewall for every port.

**Comment by bitdruid** [comment]
> Hi, Is there anyone found the solution for this issue? I try to set up an apache2 proxy to make the webui work, but no luck.
> 
> I tried several different config, this is the last one: ProxyPass /wgui/ http://127.0.0.1:5000/ <Location /wgui/> ProxyPreserveHost On ProxyPassReverse / ProxyPassReverseCookiePath / /wgui/ RewriteEngine On RewriteRule ^/wgui$ /wgui/ [R]
> 
> ```
> # Set headers
> RequestHeader set Host $host
> RequestHeader set X-Real-IP $remote_addr
> RequestHeader set X-Forwarded-Proto $scheme
> RequestHeader set X-Forwarded-For $proxy_add_x_forwarded_for
> RequestHeader set X-Forwarded-Host $server_name
> RequestHeader set X-Forwarded-Port $server_port
> ```
> 
> The goal is that my webserver is serving many different things like cups, pihole, transmission webui, and every time I just create an apache reverse proxy, and don't open the firewall for every port.

subdir is working fine for me but i can only serve you with an nginx example.

env for wireguard-ui:
`      - "BASE_PATH=/subdir1/wireguard-ui/"`

nginx directive:

```
location /subdir1/ {
    include snippets/authelia-location.conf;
    index index.html index.htm index.php;
    allow x.x.x.x/y;
    allow x.x.x.x;
    allow ::1;
    deny all;
    location ~ ^/subdir1/[^/]+\.php$ {
        include snippets/fastcgi.conf;
    }
    #location /subdir1/app1/ {
    #    proxy_pass http://x.x.x.x:7001/;
    #    proxy_redirect / /subdir1/app1/;
    #}
    location /subdir1/pihole/ {
        proxy_pass http://x.x.x.x:7001/admin/;
    }
    location /subdir1/wireguard-ui/ {
        proxy_pass http://x.x.x.x:7000/subdir1/wireguard-ui/;
    }
    location /subdir1/app4/ {
        proxy_pass http://127.0.0.1:7007;
    }
    location /subdir1/app5/ {
        proxy_pass http://127.0.0.1:9060/;
    }
    location /subdir1/app6/ {
        proxy_pass http://127.0.0.1:7008/;
        include snippets/proxy-websocket.conf;
    }
}
```

**Comment by SCH00N3R** [comment]
This is your answer right here. As bitdruid pointed out, setting BASE_PATH is most likely what you are looking for. That would be set in your docker start command or within your docker-compose.yml file
