### ISSUE TITLE
Status - operation not permitted(

### ISSUE THREAD

**Issue by Apollograph** [ngoduykhanh/wireguard-ui#373]
Hi all.

I ran into a problem, the whole system works fine, but when I click the status button in the interface, I get the error "operation not permitted".

Tell me how to fix this?
![Screenshot_1](https://github.com/ngoduykhanh/wireguard-ui/assets/105162081/b143f87c-89d4-446f-8cac-a3a05b859ad7)

**Comment by joeroback** [comment]
search.. https://github.com/ngoduykhanh/wireguard-ui/issues/176
