### ISSUE TITLE
Handling 100+ groups? (+1 master)

### ISSUE THREAD

**Issue by PizzaProgram** [ngoduykhanh/wireguard-ui#374]
Sorry, I'm new to WireGuard, and this UI looks great!
The big question is:
 - Can it handle somehow multiple separated groups
  _(for small businesses / pizzerias, to see **only their own** group members in their subnet)_ 
 - Plus 1 "master-group" for my own devices to see ALL of the clients?

No PCs should ever allowed to go to the internet through the VPN, but only see the other PCs + phones in the same group.
```
10.11.1.0/24 BestPizzaShop-Town1
10.11.2.0/24 PepperoniPizzaShop-Town2
...
10.11.252.0/16 MASTER group << to rule them all ;-)
```

Is it possible to setup/handle with this UI ? (on Debian VPS)
_(PS: I'm an experienced sysadmin + programmer, tried EtherSoft + OpenVPN before, but I'd like to switch to WG.)_

Thanks for any help / exerience!

**Comment by sekyHC** [comment]
this will need to be done via iptables
https://gist.github.com/qdm12/4e0e4f9d1a34db9cf63ebb0997827d0d

**Comment by PizzaProgram** [comment]
> this will need to be done via iptables

Thanks for the tip, but it is an impossibly huge job to do it manually with iptables on this scale.
My conclusion is that Wireguard itself is not capable to do this on it's own, there must be some kind of extra layer-controller.
Currently I'm trying to solve this with [headscale](https://github.com/juanfont/headscale) which is a wireguard based free controller.
