### ISSUE TITLE
New HEALTHCHECK CMD failing to parse URL

### ISSUE THREAD

**Issue by mikeh** [ngoduykhanh/wireguard-ui#375]
This relates to the changes made in #295

Since pulling this latest image, docker is reporting the wireguard-ui container as `unhealthy`
```
$ docker ps -a
CONTAINER ID   IMAGE                             COMMAND         CREATED        STATUS                      PORTS                                                                                                             NAMES
4e0ac968e98e   ngoduykhanh/wireguard-ui:latest   "./init.sh"     18 hours ago   Up 10 minutes (unhealthy)                                                                                                                     wireguard-ui
```

Looking at the output generated by Docker:
```
$ docker inspect wireguard-ui --format "{{ (index (.State.Health.Log) 0).Output }}"
wget: bad address '127.0.0.1:$(echo ${BIND_ADDRESS:-5000} | cut -d ':' -f2)'
```

Environment is Ubuntu 20.04.06 LTS with Docker version 24.0.1, build 6802122

I administer my containers using Portainer, but I don't believe that to be a factor here.

**Comment by djarbz** [comment]
I apologize, my testing wasn't from DOCKERFILE, but rather command line, which in this case is slightly different.
We need to call the shell first, as `sh` doesn't seem to be expanding the command properly, this should do the trick.

HEALTHCHECK CMD ["ash", "-c", "wget --output-document=- --quiet --tries=1 http://127.0.0.1:$(echo ${BIND_ADDRESS:-5000} | cut -d ':' -f2)/_health"]

**Comment by mikeh** [comment]
Thanks for the quick response. And apologies for the delay in mine - had to do a quick crash-course in Docker development and remote hosts!

I can confirm calling teh shell first fixes the healthcheck.

Are you happy with me submitting a PR for this, or would you prefer to? Don't want to steal credit for the fix.

**Comment by djarbz** [comment]
Go ahead.

**Comment by bflance** [comment]
i was able to fix the healthcheck in docker-compose.yaml file by adding this:

`  healthcheck:
      test: ["CMD-SHELL",  "/usr/bin/wget --output-document=- --quiet --tries=1 http://127.0.0.1:5000/_health"]
      interval: 10s
      timeout: 10s
      retries: 2
      start_period: 20s`

yes, i know it doesnt have variables such as ${BIND_ADDRESS:-5000} etc, but its quick and dirty hack and it works..

for some reason variables inside healthcheck didnt play well and docker was complaining about interpolation and other weird errors..

**Comment by ngoduykhanh** [comment]
healthcheck got removed in https://github.com/ngoduykhanh/wireguard-ui/pull/382
