### ISSUE TITLE
issue passing traffic?

### ISSUE THREAD

**Issue by killmasta93** [ngoduykhanh/wireguard-ui#377]
HI Currently installed the docker compose of linuxserver.yml
the client connects and shows the connected user but no traffic passes by when i try to ping or access
not sure what i missed?

Thank you

**Comment by birdyfly** [comment]
I have the same issue, clean Debian Bullseye installation and after install of Wireguard-UI no traffic passes by.

**Comment by wonka929** [comment]
I'm still having the issue.
The my file looks like that:
`{
	"addresses": [
		"10.8.0.1/24"
	],
	"listen_port": "51820",
	"updated_at": "2023-08-23T19:01:31.191690156Z",
	"post_up": "iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; ",
	"post_down": ""
`
`sudo docker exec 1070f8f76518 ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:02  
          inet addr:172.17.0.2  Bcast:172.17.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2841 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3345 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:401423 (392.0 KiB)  TX bytes:17261119 (16.4 MiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
`

Still i cannot get internet connection on clients.
What can be the issue?

**Comment by wonka929** [comment]
No, seems like i cannot ping any device on the VPN network.
Neither the ip of the container, nor any other.

**Comment by killmasta93** [comment]
@archef2000 yeah same issue tried the following wont work

**Comment by killmasta93** [comment]
i seems i had to reboot and started to work
