### ISSUE TITLE
Disable client not working

### ISSUE THREAD

**Issue by ecsuae** [ngoduykhanh/wireguard-ui#38]
if i disable client and apply config, still the client is connected, how can i temporary block a client?Also guide how to change the default web username and password?can we see login history of client? can we get telegram or any other monitoring alert for user login and logout? 
If i get answers to my problems i will buy you afew cofee :)

**Comment by ngoduykhanh** [comment]
Hi,
When you disable a client and apply the config, wireguard-ui will write a new server config file. If your wireguard server got restarted properly, the client should be disconnected. Please verify if it was restarted. See README for a method to reload the wireguard server when its config changed.
You can change the login credential by editing file `db/server/users.json`
For now, there is no feature to show client login history yet.

**Comment by ecsuae** [comment]
Thanks for the response, can you guide any solution to monitor client login history? do you have plans to implement it?Can you guide how can i use wireguard-ui in a working server where already so many client keys exist?

**Comment by ngoduykhanh** [comment]
As far as I know Wireguard itself doesn't have any feature to show the client login time/history. `wg show` command shows the `latest handshake`, maybe it is helpful for you?
Currently, Wiguard-UI will write a new config file from its own data. We don't have a feature to import an existing config file yet.

**Comment by ecsuae** [comment]
i need to access a network device in wireguard client network i am adding the ip in allowed ips but it is not added in wg0.conf, while it show the ip added in web, i tried to restart manually restart wireguard as well, but it is still same not added to conf file.I need it to be added as 
AllowedIPs =10.8.0.7/32, 192.168.101.30/32
where 10.8.0.7 is client ip and 192.158.101.30 is network need to be accessed through this client.
