### ISSUE TITLE
[FEATURE REQUEST] User Profile Based Firewall-ing

### ISSUE THREAD

**Issue by christoboucher** [ngoduykhanh/wireguard-ui#380]
Good Day,

I am loving you Wireguard-UI product and have recently switched to using it.

I would like to make a suggestion that we would love to see and be able to use and I am sure will enhance the reach and functionality of your product, not just for use but for a wide variety of use cases out there.

**SCENARIO**
We would like to have a central Wireguard VPN server that everyone and anyone that needs access to some service inside our network can connect to to gain access to what ever they need.

However, not everyone should be given access to everything that everyone else should be able to access.

**SUGGESTION**
If there was a way to define Firewall Profiles and set the Allowed IP and ports for that profile, then add the user to the Firewall Profile.

This in turn will set the IPTables Rules when the user connects, restricting them being able to access only what they are allowed to access.

A user can belong to more than one Firewall Profile?

Please consider this as I think it will enhance your product.

Kind Regards
Christo

**Comment by ngoduykhanh** [comment]
Hi, thank you for your suggestion. It is a valid idea. However, Wireguard is not designed to have any firewall capability I think. The AllowIP set in the user profile can be modified easily by the user. I get your ideas about configuring IPtables on the Server side to apply the restriction, but it is complex. I don't want to develop the Wireguard-UI in the direction that needs to manage complex IPtables rules to fit several scenarios.
