### ISSUE TITLE
wiregurad fails after Stop/start docker-compose

### ISSUE THREAD

**Issue by rcitton** [ngoduykhanh/wireguard-ui#381]
Running on raspberry PI4, leveraging on "examples/docker-compose/linuxserver.yml" and having a wg0.conf, after a stop/start im getting:
.
**** It seems the wireguard module is already active. Skipping kernel header install and module compilation. ****
**** Client mode selected. ****
[custom-init] No custom files found, skipping...
**** Disabling CoreDNS ****
wg-quick: `wg0' already exists
s6-rc: warning: unable to start service svc-wireguard: command exited 1
.
svc-wireguard works if I remove wg0.conf.
---
From inside the container:

root@ae5443d86731:/# wg-quick up /config/wg0.conf 
wg-quick: `wg0' already exists
root@ae5443d86731:/# echo $?
1   <<--- !!!

root@b88dc7f3c803:/# wg-quick down wg0
[#] ip link delete dev wg0
[#] iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
root@b88dc7f3c803:/# wg-quick up /config/wg0.conf 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.252.1.0/24 dev wg0
[#] ip link set mtu 1450 up dev wg0
[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
root@b88dc7f3c803:/#

**Comment by rcitton** [comment]
Looks like wireguard-ui start wg0 device and later when wireguard container is coming up running wg-quick with wg0 already up it fails..

**Comment by rcitton** [comment]
WGUI_MANAGE_START=false solve

**Comment by hanscees** [comment]
this solves it, but also disables port 5000 in my environment.
So not working http now?

**Comment by chrgraham** [comment]
Hit this same issue after migrating to a machine with a much faster CPU, then Google'd my way here and saw the comment about a race condition. I solved it by asking ChatGPT "what is a docker compose healthcheck I can run against a wireguard container"

This solution adds a solid delay for wireguard to startup and be reported as healthy before wireguard-ui will start.

Add this to `wireguard`
```
    healthcheck:
      test: ["CMD", "/config/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
```

Add this to `wiregaurd-ui`
```
    depends_on:
      wireguard:
        condition: service_healthy
```

And add this script to the `wiregaurd` config volume.  Your `<interface-name>` is likely `wg0`. Don't forget to `chmod +x healthcheck.sh`
```
#!/bin/bash

# Check if the WireGuard interface is up
if ip link show <interface-name> &> /dev/null ; then
    exit 0 # The interface is up, so the container is healthy
else
    exit 1 # The interface is down, so the container is unhealthy
fi
```

You can shell into the Wiregaurd container and manually execute the script.

**Comment by bverkron** [comment]
Is this seriously the "fix"? Not knocking your suggestion @chrgraham but the fact that there is an inherent race condition in this setup and a bunch of this work has to be done to make the docker setup usable seems crazy to me.

**Comment by cgraham-rs** [comment]
> Is this seriously the "fix"? Not knocking your suggestion @chrgraham but the fact that there is an inherent race condition in this setup and a bunch of this work has to be done to make the docker setup usable seems crazy to me.

No argument from me. 

I have healthchecks enabled for a variety of my containers so it was a good workaround for me.

@rcitton has a different and much more simple workaround posted.

**Comment by chrgraham** [comment]
> Is this seriously the "fix"? Not knocking your suggestion @chrgraham but the fact that there is an inherent race condition in this setup and a bunch of this work has to be done to make the docker setup usable seems crazy to me.

No argument from me. 

I have healthchecks enabled for a variety of my containers so it was a good workaround for me.

@rcitton has a different and much more simple workaround posted.

**Comment by bverkron** [comment]
Well, that might work to prevent the race condition but it also disables the UI from what I understand from the other comments and my brief testing. Which, if true, defeats the whole purpose of running the ui in the first place. I also tried starting up the UI when the conflict was happening to see if I could at least config it with the UI and then disable the UI to run wg but the UI failed to load.
