### ISSUE TITLE
I tried to build the image on Raspberry Pi and got this error:

### ISSUE THREAD

**Issue by operationairstrike** [ngoduykhanh/wireguard-ui#383]
---> Running in e2382c6f644e
standard_init_linux.go:219: exec user process caused: exec format error
The command '/bin/sh -c apk add --update --no-cache ${BUILD_DEPENDENCIES}' returned a non-zero code: 1

**Comment by archef2000** [comment]
What PI do you have and why do you not just use the prebuild one on [DockerHub](https://hub.docker.com/r/ngoduykhanh/wireguard-ui/tags)

**Comment by operationairstrike** [comment]
I didnt know this exist😭.
And I have Raspberry Pi 4 Model B 4GB Ram
