### ISSUE TITLE
Strange DNS query

### ISSUE THREAD

**Issue by alex27riva** [ngoduykhanh/wireguard-ui#387]
Hi everyone, in my network I use PiHole and I noticed this DNS query.
![immagine](https://github.com/ngoduykhanh/wireguard-ui/assets/5512235/4b6f1df1-dbc2-4c0c-981f-44b634b7feae)
I'm pretty sure it's coming from the Wireguard-u container because the port is 5000.

**Comment by ngoduykhanh** [comment]
Interesting, it could come from some other software on your PiHole. Try changing the port of wireguard-ui to another one and check if the same query is still there.
