### ISSUE TITLE
The hash in db/server/users.json stopped working after update from 4.0 to 5.1

### ISSUE THREAD

**Issue by Akuna-Tarata** [ngoduykhanh/wireguard-ui#395]
Hello together!

I just updated my instance of wireguard-ui from v4.0 to v5.1.
After restarting the webinterface, it is only accessable with the standard-password "admin".
Under version 4.0 I used successfully a hashsum which I put under db/server/users.json like here:
`{
        "username": "admin",
        "password": "",
        "password_hash": "HERE IS MY HASHSUM"
}
`
after the update to 5.1 it stopped working

What was changed here?

**Comment by ngoduykhanh** [comment]
The DB folder structure was changed. For user db, they are stored under `./db/users/` directory. In your case, it should be something like `./db/users/admin.json` which has the following content
```
{
	"username": "admin",
	"password": "",
	"password_hash": "THE HASH",
	"admin": true
}
```
