### ISSUE TITLE
No Connection 

### ISSUE THREAD

**Issue by hiduser0** [ngoduykhanh/wireguard-ui#397]
Hey,

I running the Wireguard Container with Wireguard-UI and Wireguard. I can apply settings through the webif, but if I connect with the client config file, I don’t have access to the Internet or the Server anymore.
If do ifconfig, there is no wg0 interface. 
What is wrong?

**Comment by tgudlek** [comment]
I've spent a good amount of time today fighting this.

It seems to me that `wireguard-ui` puts the CIDR address into the `Address` field `wg0.conf`, which `wireguard` refuses to accept.

Trying opening your `wg0.conf` and change `Address = 10.252.1.0/24` to `Address = 10.252.1.1`. Also, if there are any peers in your file, make sure none of them have `10.252.1.1` as their IP address.

Doing this and restarting `wireguard` has solved the issue for me.

**Comment by hiduser0** [comment]
Thank you that helps for me too!
