### ISSUE TITLE
Add clients manually

### ISSUE THREAD

**Issue by simplayy** [ngoduykhanh/wireguard-ui#398]
II'm trying to manually add a client, but it doesn't appear on the web page. 
Only the ones generated by the UI are visible, Is this normal or is it a problem on my end? 
If so, is there a way to manually add a configuration through the terminal and make it appear in the UI as well?

Thanks

**Comment by archef2000** [comment]
I tested it by copying a client `*.json` and changing the id in the file the same as the file name, pri/pub key and ip and reload the web interface and so it showed up and the only thing i needed to do is press apply config
