### ISSUE TITLE
cannot add some IPv6 addresses

### ISSUE THREAD

**Issue by shizunge** [ngoduykhanh/wireguard-ui#40]
Cannot add some IPv6 addresses as server ip or client ip.

Working examples: `fabc:1234::/64`, `fabc:1234::2/128`

Non-working examples: `fabc:1234:5678::/64`, `fabc:1234:5678::2/128`

**Comment by ngoduykhanh** [comment]
Hi,
What do you mean by server IP and client IP?
Those examples didn't work because of `/64` and `/128` character I think. Try to remove it. Also, the error is returned from PDNS though

**Comment by shizunge** [comment]
Should we turn this bug into a feature request instead of closing it?
