### ISSUE TITLE
Low data transfer rate with wireguard-ui.

### ISSUE THREAD

**Issue by Dr4tez** [ngoduykhanh/wireguard-ui#400]
After installing and configuring wireguard-ui, the download speed through wireguard decreases by 2 times, and the upload speed decreases by 5 times than before it was installed. Wireguard-ui Installed as a binary file. Am I the only one with this problem? Because of what it can occur and how to solve it, except for the way not to install wirguard-ui?

**Comment by Dr4tez** [comment]
2 VPS on Ubuntu 20.04 and Ubuntu 22.04.

**Comment by afzl-wtu** [comment]
> After installing and configuring wireguard-ui, the download speed through wireguard decreases by 2 times, and the upload speed decreases by 5 times than before it was installed. Wireguard-ui Installed as a binary file. Am I the only one with this problem? Because of what it can occur and how to solve it, except for the way not to install wirguard-ui?

try to remove MTU so that it will be auto in config file.

**Comment by Dr4tez** [comment]
> > After installing and configuring wireguard-ui, the download speed through wireguard decreases by 2 times, and the upload speed decreases by 5 times than before it was installed. Wireguard-ui Installed as a binary file. Am I the only one with this problem? Because of what it can occur and how to solve it, except for the way not to install wirguard-ui?
> 
> try to remove MTU so that it will be auto in config file.

Thank you. It really helped. It didn't even cross my mind that it was MTU.
