### ISSUE TITLE
Installation next to a working wireguard

### ISSUE THREAD

**Issue by smiell** [ngoduykhanh/wireguard-ui#402]
Hey, how do I use wiregaurd-ui alongside an already working Wireguard setup? I don't want to reinstall wiregaurd. I would like to run wireguard-ui in a container next to an already running wiregaurd server. Is it possible?

**Comment by archef2000** [comment]
It is possible but difficult as you would need to create the "database" with all the existing data by:
- running the wireguard-ui and wireguard-server
- changing the priv/pub key in the wireguard server settings to the existing one
- adding all old clients and entering the existing pub/psk
- shutting down the old wg-server
- changing the port to the old one
- apply the config
- hopping you made no mistake and all old clients can connect

**Comment by hanscees** [comment]
the is a guide here that does that
https://linuxiac.com/how-to-set-up-wireguard-vpn-with-docker/#comment-39615

however, after adding the first client it stops working ..

**Comment by GovSat1** [comment]
Tagging on to this, there is no way to monitor an external wireguard server with wireguard-ui is there? Running directly on firewall in my case.

**Comment by archef2000** [comment]
> Tagging on to this, there is no way to monitor an external wireguard server with wireguard-ui is there? Running directly on firewall in my case.

No not really as you need the config for the server and a way to reach the client devices and maybe more
