### ISSUE TITLE
Conection is made, but no host is reachble

### ISSUE THREAD

**Issue by MajliTech** [ngoduykhanh/wireguard-ui#407]
Hi, 
I just done [this setup](https://github.com/ngoduykhanh/wireguard-ui/tree/master/examples/docker-compose). However, no host is reachble, and the admin panel shows "connected".
Here's the config:
```ini
[Interface]
Address = 10.252.1.2/32
PrivateKey = ********************************************
DNS = 192.168.12.61,1.1.1.1
MTU = 1450

[Peer]
PublicKey = ********************************************
PresharedKey = ********************************************
AllowedIPs = 0.0.0.0/0
Endpoint = home.majlitech.pl:51820
PersistentKeepalive = 15
```
The port is open.
What should I do? I know that this is not priority support, but I'm going away on Monday, so it would be nice if someone could help by then.

**Comment by MajliTech** [comment]
Reddit helped. Fixed.

**Comment by AhmedNabil1992** [comment]
> Reddit helped. Fixed.

Could you please let me know how to solve it or mention link because i have same issue ,
thanks in advance ,.

**Comment by Nevah5** [comment]
https://www.reddit.com/r/WireGuard/comments/1504lm1/conection_is_made_but_no_host_is_reachble/
