### ISSUE TITLE
SSO via OIDC Support

### ISSUE THREAD

**Issue by victorrodriguez1984** [ngoduykhanh/wireguard-ui#408]
Maybe we can add this feature for administration 
https://github.com/zhaow-de/pam-keycloak-oidc

**Comment by L11R** [comment]
@victorrodriguez1984 this is PAM module to use in Linux. For SSO it's enough standard golang.org/x/oauth2 package.

**Comment by victorrodriguez1984** [comment]
Good Thank you!

**Comment by FarhadF** [comment]
why is this marked as completed? can you please link the merge request or documentation that shows how the SSO works.

**Comment by friesoft** [comment]
This should be reopened and proper oidc support implemented
