### ISSUE TITLE
[FEATURE REQUEST] 2FA

### ISSUE THREAD

**Issue by ZMJGMADHPXWT** [ngoduykhanh/wireguard-ui#414]
Hi. 
Thank you for helpful project. Is it possible to add 2 factor auth for WG users?
For example when user connect to WG server, he will be redirected to web-page where he have to type 6 digits from 2FA Android/iOS app. After that firewall will allow his traffic.

Thanks in advance.

**Comment by ZMJGMADHPXWT** [comment]
?

**Comment by goldmont** [comment]
Hi,

News about this? Password-only authentication is too weak.
