### ISSUE TITLE
how to add server as a wireguard node

### ISSUE THREAD

**Issue by benzking** [ngoduykhanh/wireguard-ui#419]
how to add server as a wireguard node
now server is not a  wireguard node ,my device no public network ipv4 ip，can't interconnected
i want to the server is a node，and rout vpn

**Comment by lonesomewalker** [comment]
it is called site2site

**Comment by jantschaefer** [comment]
A site-to-site configuration could be easily implemented by adding an additional field to the client configuration in the user interface (UI). If this field is filled out, it will append an additional line to the peer configuration in the wg0.config file.

The additional line should follow the format:

Endpoint = ip or url : port

This issue has been raised multiple times, as seen in issues #168 and #313, but it has not been implemented yet.

**Comment by angellietor** [comment]
Is there a plan to add site-to-site soon?
I need to interconnect two office locations.

Thanks !!
