### ISSUE TITLE
linuxserver/wireguard not working with wireguard-ui

### ISSUE THREAD

**Issue by jonrub** [ngoduykhanh/wireguard-ui#42]
I am using Wireguard via linuxserver/wireguard docker container. When I setup Wireguard-UI I have to set Server interface addresses in cidr format and then it is not working for me. If I edit wg0.conf via cli and remove the /32 from the Interface address it is working. 

Can you please allow only IP also?

**Comment by jonrub** [comment]
Must have been something in wrong in my setup. It is working now.

**Comment by zmiguel** [comment]
Can you explain how you got this to work with linuxserver/wireguard? Thanks.

**Comment by Kawabountou** [comment]
Hello

Could you explain your solution. (your docker-compose for example)

I have the same docker, and I would like to do the same.

Thank you in advance.
