### ISSUE TITLE
PersistentKeepAlive setting is not set to peers in server configuration

### ISSUE THREAD

**Issue by mhooSec** [ngoduykhanh/wireguard-ui#432]
Hello,

In Global Settings section of wireguard-ui, if we specify a value in "Persistent Keepalive", the defined value appears in the client configuration file that we can download from the "WireGuard Clients" section, but not in the server configuration file. 

In order to maximize peer reachability when there is NAT or a firewall present, "PersistentKeepAlive" should be on both ends, "server" and "peer".

We can reproduce this by:
1) Setting a value in "Persistent Keepalive", in Global Settings section of wireguard-ui. Click save.
2) We can try to "Apply config" by heading to another section, as for some reason "Apply Config" button does not show in "Global Settings" section. This should re-write the server configuration file with all the saved options.
3) We can inspect the contents of the server configuration file in `/etc/wireguard/wg0.conf`. We will observe there is no trace of PersistentKeepAlive in any peer.
4) However, if we download the configuration file of a client in "WireGuard Clients", we will observe the defined value for "Persistent Keepalive" in Global Settings is shown here.

I suspect that a manual override of `/etc/wireguard/wg0.conf` in the server will be wiped out once we "Apply changes" via the GUI, but this has not been tested yet.

Thank you for your attention.

**Comment by jantschaefer** [comment]
Thank you. I would also highly appreciate the option to include the PersistentKeepAlive setting in the configuration. I am running a site-to-site configuration, and the connection between both sides is unstable if PersistentKeepAlive is not specified on either of the sites.
