### ISSUE TITLE
Network not working on Hetzner VPS template

### ISSUE THREAD

**Issue by pietrodicaprio** [ngoduykhanh/wireguard-ui#459]
Hello, like #312 , I can't get Wireguard to work using the Hetzner template.

I pressed the "apply config" button after creating a client, tried to reboot the server, installed all the updates via `apt`: nothing changed. The client connects but then can't use the network, not even to ping the internal address of the VPN server (172.30.0.1).

Hetzner explains it as a trivial task in their documentation but... https://docs.hetzner.com/cloud/apps/list/wireguard/

Did anyone else face this issue and found a solution? It looks like a routing issue.

**Comment by ElForastero** [comment]
Well, I think their docs are missing a step with setting up a firewall to allow incoming UDP traffic on the wireguard server port.

Like this:

<img width="1512" alt="image" src="https://github.com/ngoduykhanh/wireguard-ui/assets/5102818/6a45b94a-8bc8-41fe-b85b-fbfb01018a2f">

P.S. This firewall should also be **applied** to the server, not only created.
