### ISSUE TITLE
[Feature Request] mail config to user's email

### ISSUE THREAD

**Issue by changchichung** [ngoduykhanh/wireguard-ui#46]
Since the user's email address was entered when the client config was created, can you add a function to mail config to the user ?
I think it will be more convenient for management.

**Comment by ngoduykhanh** [comment]
Yes, it was my intention to have that kind of feature when having email input. Unfortunately, I don't have much time to work on it. I will see if I can do it soon.

**Comment by kking124** [comment]
Could this be implemented using a one time download and/or expiring link instead? Something like:

https://domain.local/download/client.conf?q=SOME_REALLY_LONG_STRING_IDENTIFIER_FOR_ONE_TIME_USE_OR_TIMED_EXPIRATION

I don't like the idea of configurations floating around in email addresses.

**Comment by gosom** [comment]
@changchichung This is implemented now.
@ngoduykhanh I think that you can close this issue.

Best
