### ISSUE TITLE
Exporting a client's configuration from Android produces a .txt file

### ISSUE THREAD

**Issue by Yann39** [ngoduykhanh/wireguard-ui#462]
Exporting a client's configuration from Android gives a `.txt` file, while exporting the same client config from Windows gives a `.conf` file.

Renaming the file extension to `.conf` does the job, I've successfully imported it into the Wireguard client.

But I was just wondering if that was intended, as the Wireguard client only accepts `.conf` or `.zip` files.

**Comment by MiguSchweiz** [comment]
A temporary fix is replacing mime type "text/plain" with "text/conf" in file:
handler/routes.go:              return c.Stream(http.StatusOK, "text/conf", reader)

then rebuild wireguard_ui
