### ISSUE TITLE
[Help] Stop wireguard-ui from exposing to outer internet in linuxserver.yml

### ISSUE THREAD

**Issue by TissuePowder** [ngoduykhanh/wireguard-ui#486]
I am using https://github.com/ngoduykhanh/wireguard-ui/blob/master/examples/docker-compose/linuxserver.yml

It exposes wireguard-ui port 5000 to 0.0.0.0, so anyone with my vps ip can access the ui at `http://vps_ip:5000/`. But I don't want that. I want to reverse proxy the ui through nginx, so I want it at most to be accessible from the host network.

But doing `127.0.0.1:5000:5000` isn't working since the network_mode for ui is set to `servie:wireguard`. So what should I do to make the ui accessible only from the host keeping the network_mode as it is? Any help would be appreciated.

**Comment by Paillat-dev** [comment]
> I am using https://github.com/ngoduykhanh/wireguard-ui/blob/master/examples/docker-compose/linuxserver.yml
> 
> It exposes wireguard-ui port 5000 to 0.0.0.0, so anyone with my vps ip can access the ui at `http://vps_ip:5000/`. But I don't want that. I want to reverse proxy the ui through nginx, so I want it at most to be accessible from the host network.
> 
> But doing `127.0.0.1:5000:5000` isn't working since the network_mode for ui is set to `servie:wireguard`. So what should I do to make the ui accessible only from the host keeping the network_mode as it is? Any help would be appreciated.

You should reverse the linuxserver wireguard container's 5000 port into nginx. If nginx is in a docker container (wich I will assume here), you should put them into the same network, and reference to the container's name : container port in nginx. For example: `http://wireguard:5000`

**Comment by TissuePowder** [comment]
Oh I forgot to close this issue. There was some unknown temporary error at my side, it's been solved.

@Paillat-dev I am running nginx on the host for reverse-proxy'ing just about anything. Docker, non-docker, normal apps etc. There was probably some config problem on my compose file which I don't exactly remember now.
