### ISSUE TITLE
can you remove  static files(css/fonts...) which are load from Internet

### ISSUE THREAD

**Issue by DalekFrog** [ngoduykhanh/wireguard-ui#49]
I run wireguard-ui in a offline enviromment. 
client can not load the css from `https://code.ionicframework.com`,`https://fonts.googleapis.com/`

**Comment by SephGER** [comment]
You can try [this](https://github.com/ngoduykhanh/wireguard-ui/compare/master...SephGER:master) out

**Comment by zilexa** [comment]
I second this, for some reason, when I try to access the webUI via browser on my server itself, it is always stuck on loading googleapis.com fonts. Takes a very long time.
