### ISSUE TITLE
RIghts for non-privileged users

### ISSUE THREAD

**Issue by hr1232** [ngoduykhanh/wireguard-ui#495]
ATM there are two access levels. Admins see all, Managers just see (and can edit) Client configs.

Please give us a third access level for users who only see their own config(s). Configs could have an optional owner-setting which should be a dropdown-list of all user accounts. Users should then be able to login and ownload their config or show their QR code without being able to change anything.

**Comment by ngoduykhanh** [comment]
Hello,

Wireguard-UI is not designed for a self-service model. It is designed for a single tenant or provider to manage their client's config and have different options to deliver the config to their user.
