### ISSUE TITLE
Unable to login // users.json missing

### ISSUE THREAD

**Issue by RaduMC** [ngoduykhanh/wireguard-ui#50]
I've downloaded the latest release (non-docker) on my Ubuntu system.
I can access the web interface but cannot login. The login page returns the error "Cannot query user from DB".

Looking at /db/server/ there is no users.json created with default admin/admin credentials.
Am I supposed to create this file myself? If so, what is the format?

Or maybe it's related to the error "Cannot init database".
Ubuntu is running in a virtual environment with 2 bridged network interfaces. Wireguard is pre-installed and running.

```
radu@icarus:~$ ./wireguard-ui 
Wireguard UI
App Version	: v0.2.7
Git Commit	: b8142b80c235753e501376e21d3694cd066d977c
Git Ref		: refs/tags/v0.2.7
Build Time	: 03-10-2021 08:19:07
Git Repo	: https://github.com/ngoduykhanh/wireguard-ui
Authentication	: true
Bind address	: 0.0.0.0:5000
Cannot init database: no IP could be found⇨ http server started on 0.0.0.0:5000
{"time":"2021-03-10T10:19:21.790763328+02:00","id":"","remote_ip":"192.168.10.18","host":"192.168.10.17:5000","method":"GET","uri":"/login?next=/","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","status":200,"error":"","latency":191200,"latency_human":"191.2µs","bytes_in":0,"bytes_out":4877}
{"time":"2021-03-10T10:19:35.775285385+02:00","id":"","remote_ip":"192.168.10.18","host":"192.168.10.17:5000","method":"POST","uri":"/login","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15","status":500,"error":"","latency":611746,"latency_human":"611.746µs","bytes_in":39,"bytes_out":55}
```

**Comment by Maeljd** [comment]
Hi,

I had the same trouble.
In my case the problem was my firewall config. Blocking 80 output.
The binary seems to need some download at the first start. Especially for the database init.

Hope can be helpful.
Maël

**Comment by Nobody84** [comment]
Same issue running the in a docker container using the docker-compose file.

**Comment by DeerMaximum** [comment]
Hey,
the format for the users.json is:
```json
{
      "username": "admin",
      "password": "admin"
}
```

**Comment by mdotgru** [comment]
Had the same issue. It turned out that I just needed to change the permissions to the user.json or run the systemd wireguard-ui service as a more privileged used.
