### ISSUE TITLE
port forwarding through vpn

### ISSUE THREAD

**Issue by secretdk** [ngoduykhanh/wireguard-ui#503]
Is there an option to be able to do port forwarding for different clients, it's just a features request

**Comment by nebulosa2007** [comment]
According this [article](https://www.procustodibus.com/blog/2022/09/wireguard-port-forward-from-internet/) it can be done now without any new features..

**Comment by nebulosa2007** [comment]
WireGuard-ui it's just wg.conf generator. You need just fill up `PreUp` and `PostDown` strings at server settings.

**Comment by ngoduykhanh** [comment]
I have the same thought as @nebulosa2007 . Wireguard-UI is an interface for managing WireGuard configuration. It isn't designed to work as an interface to manage a router or gateway.
