### ISSUE TITLE
Cannot verify password (WireGuard UI) not working

### ISSUE THREAD

**Issue by scott-mackenzie** [ngoduykhanh/wireguard-ui#514]
**Cannot verify password (WireGuard UI) not working**

**Using binary file** Install method on below Ubuntu VM

root@ns1:/opt/wireguard-ui/db/users# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

===========================================

root@ns1:/opt/wireguard-ui/db/users# ls -l
total 4
-rw-r--r-- 1 root root 152 Dec 30 18:11 admin.json

===========================================

root@ns1:/opt/wireguard-ui/db/users# cat admin.json
{
	"username": "admin",
	"password": "admin",
        "password_hash": "$2y$14$FUQ3eH09sDyuShguU0/Hd.v4fLWuqiTJlmgutjbpit/GenDvZ8iS.",
	"admin": true
}

password_hash created by: https://bcrypt.online/ with cost factor 14

==========================================

<img width="451" alt="Screenshot 2023-12-30 at 7 44 06 PM" src="https://github.com/ngoduykhanh/wireguard-ui/assets/1774915/e78e927d-feb6-4fe9-94d6-48d70cbb9621">

==========================================

This is a fresh install based on defaults.  Any idea on what HASH value it seeks by default or suggestions to resolve?

**Comment by ngoduykhanh** [comment]
You must do base64 encoding of the hashed password from https://bcrypt.online before saving it to the `password_hash` field.

**Comment by scott-mackenzie** [comment]
Confirmed.  

Used https://www.base64encode.org for base64 encoding and it worked.
