### ISSUE TITLE
Unable to install?

### ISSUE THREAD

**Issue by chaoticdude** [ngoduykhanh/wireguard-ui#517]
Hello,
Relatively new to WireGuard. Need some help if you please.
I am using the following DigitalOcean image:

https://marketplace.digitalocean.com/apps/pi-hole-vpn

This image contains WireGuard with no configuration on my part necessary. I would love to utilize the WebUI found here. This is what I have done from terminal (screenshot attached).

its not installing. what am i doing wrong?

![Screenshot 2023-12-31 13 49 30](https://github.com/ngoduykhanh/wireguard-ui/assets/22921203/c8bf3110-35b4-452a-97b2-a24ca41e390f)

**Comment by ngoduykhanh** [comment]
If you run the wireguard-ui from binary, please ensure you downloaded the correct built version compatible with your VM's CPU arch.

**Comment by chaoticdude** [comment]
Ok thanks!!!
