### ISSUE TITLE
Linux amd64 release v.0.6.0

### ISSUE THREAD

**Issue by nebulosa2007** [ngoduykhanh/wireguard-ui#522]
For release 0.6.0 there are no binary files for linux x86_64:  https://github.com/ngoduykhanh/wireguard-ui/releases/tag/v0.6.0

It is temporary issue or arch was dropped for building?

**Comment by ngoduykhanh** [comment]
There was a problem with FreeDBS build which canceled all other builds. I temporarily have another release to fix the Linux AMD64 first https://github.com/ngoduykhanh/wireguard-ui/releases/tag/v0.6.1

**Comment by ngoduykhanh** [comment]
Fixed in https://github.com/ngoduykhanh/wireguard-ui/pull/525. New release [v0.6.2](https://github.com/ngoduykhanh/wireguard-ui/releases/tag/v0.6.2) created.
