### ISSUE TITLE
trying to login to the webui

### ISSUE THREAD

**Issue by SprayzXD** [ngoduykhanh/wireguard-ui#523]
So I'm trying to log in with the web UI every time I go to log in with the credentials I set using the compile file it doesn't work can anyone tell me what am i doing wrong here? Update I managed to log in.

**Comment by Alex-joomla** [comment]
Same for me

**Comment by zvzz** [comment]
Anyone stumble upon this thread - do not forget to restart the UI daemon before logging in first time.

**Comment by florin-nechita** [comment]
So after the first docker-compose up -d, it wants, for some reason, a docker restart.
Almost gave up until I stumbled upon this thread.

**Comment by graves501** [comment]
Sharing this so it might help someone else out there :grin: 

I couldn't get the web UI to load... restarting the containers (using `docker-compose`) did not help.
The error in the logs was:
```
Found WG conf /config/wg_confs/wg0.conf, but it doesn't seem to be valid, skipping.
```

For whatever reason `wg0.conf` got created, but it was just an empty file. Manually removing and then restarting the containers fixed the issue :+1:

**Comment by nebulosa2007** [comment]
> So after the first docker-compose up -d, it wants, for some reason, a docker restart. Almost gave up until I stumbled upon this thread.

Got same error on a new instance but i don't use docker image, systemd service instead

After start at first time, I log in with admin admin, it shows "Logged in successfully" and nothing happened after. Restarting service helps.

Log shows nothing:
```
...
wireguard-ui[18806]: Git Repo        : https://github.com/ngoduykhanh/wireguard-ui
wireguard-ui[18806]: Authentication        : true
wireguard-ui[18806]: Bind address        : 0.0.0.0:5000
wireguard-ui[18806]: Email from        :
wireguard-ui[18806]: Email from name        : WireGuard UI
wireguard-ui[18806]: Custom wg.conf        :
wireguard-ui[18806]: Base path        : /
wireguard-ui[18806]: Subnet ranges        :
wireguard-ui[18806]: Valid subnet ranges:
wireguard-ui[18806]: ⇨ http server started on [::]:5000
systemd[1]: Stopping A web user interface to manage your WireGuard setup...
systemd[1]: wireguard-ui.service: Deactivated successfully.
systemd[1]: Stopped A web user interface to manage your WireGuard setup.
systemd[1]: wireguard-ui.service: Consumed 13.094s CPU time, 11.9M memory peak, 0B memory swap peak.
```

**Comment by nebulosa2007** [comment]
> Please test #534, should allow an immediate login

Now works as expected! Thanks!

**Comment by jearton** [comment]
Restarting container is not working for me

**Comment by xgbt** [comment]
> Sharing this so it might help someone else out there 😁
> 
> I couldn't get the web UI to load... restarting the containers (using `docker-compose`) did not help. The error in the logs was:
> 
> ```
> Found WG conf /config/wg_confs/wg0.conf, but it doesn't seem to be valid, skipping.
> ```
> 
> For whatever reason `wg0.conf` got created, but it was just an empty file. Manually removing `wg0.conf` and then restarting the containers fixed the issue 👍

delete the /config/wg_confs/wg0.conf in container linuxserver/wireguard, then restart all two containers, that work for me.

**Comment by BaptisteLecat** [comment]
> Anyone stumble upon this thread - do not forget to restart the UI daemon before logging in first time.

Thank you, I don't know why but is't mandatory...

**Comment by deanfourie1** [comment]
I also have this issue.

I have 
```
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=this-unusual-password
```
Set but cannot login with these details? Am I doing this wrong?

Thanks
