### ISSUE TITLE
How to install GUI with other WireGuard install method?

### ISSUE THREAD

**Issue by alexlii1971** [ngoduykhanh/wireguard-ui#53]
Hello,

It is important to protect dns leak, and we can achieve that by using some method like this one:

https://github.com/complexorganizations/wireguard-manager

The problem is how we set it work with WireGuard-ui or match each other please?

Thanks

**Comment by ngoduykhanh** [comment]
I've never used wireguard-manager before. As long as it has a single Wiguard config file, you can adjust the `Wireguard Config File Path` setting of wireguard-ui to make the work together.
