### ISSUE TITLE
There is a dependency issue after fixing #522

### ISSUE THREAD

**Issue by 0xCA** [ngoduykhanh/wireguard-ui#533]
![image](https://github.com/ngoduykhanh/wireguard-ui/assets/11984323/32623e91-93df-4dda-a3d8-25a9a8919a36)

When I try to go mod download, it downloads the newest version

Can't build with `golang.zx2c4.com/wireguard/wgctrl v0.0.0-20210803171230-4253848d036c`

**Comment by ngoduykhanh** [comment]
Can you try out https://github.com/ngoduykhanh/wireguard-ui/pull/535 ?
