### ISSUE TITLE
Disable Authentication

### ISSUE THREAD

**Issue by yeyeoke** [ngoduykhanh/wireguard-ui#56]
Hi, I noticed that you enabled us to disable authentication. How do I actually use this? 

Right now I've set my users.json to provide empty values for username and password but I'm still getting prompted to login. 

Using the docker-compose with the latest tag.

**Comment by flyinprogrammer** [comment]
https://github.com/ngoduykhanh/wireguard-ui/blob/024aadbfd2a48f03b833ec44d0593a95ccff0adc/main.go#L26

when you start the application binary you need to pass in the "--disable-login" as a command line flag

**Comment by jpdsc** [comment]
@flyinprogrammer I tried this by adding
`entrypoint: ["./init.sh", "--disable-login"]` or `command: --disable-login` to the docker-compose. However, still get the login screen.

Any idea?

**Comment by DieserMerlin** [comment]
Can be done by using entrypoint and not command. Just add this to your service definition in the compose file:
`entrypoint: ./wg-ui --disable-login`
Works for me :)
