### ISSUE TITLE
Configure DNS suffix for the connection

### ISSUE THREAD

**Issue by derDavid308** [ngoduykhanh/wireguard-ui#59]
Currently, I manually add the DNS suffix by hand for each client configuration file:

DNS = my.dns.server.address, dns.suffix

When I try to configure this in the UI, the error message "Invalid DNS server address" is displayed. Maybe you can make this configurable later?

Thanks in advance, I love the UI :)

**Comment by derDavid308** [comment]
I managed it by adding the suffix in the global_settings.json by hand - nevertheless, configuration in the UI would by nicer.

**Comment by zilexa** [comment]
This one should be closed, you can already configure DNS in the global settings :)

**Comment by HeinrichWarkentin** [comment]
Warum wurde dieses Issuse geschlossen? Der Kollege hat ein Workaround gefunden, doch wäre es gut wenn man diese Option in die UI einbaut.

--- English: Translated by Deepl ---

Why was this issue closed? The colleague has found a workaround, but it would be good to add this option to the UI.
