### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by gavinc-git** [ngoduykhanh/wireguard-ui#636]
How does one compile this?

I have tried with just `go build` but end up with a JSON message on screen when trying to access UI.

All I am changing is the email message in the `main.go` file

**Comment by nirajkumar999** [comment]
Try setting up the application via docker compose first.

**Comment by spetzreborn** [comment]
@gavinc-git You need to build the GUI first by running

' prepare_assets.sh ' that depends on yarn.  After you built that you just do go build.

**Comment by gavinc-git** [comment]
> Try setting up the application via docker compose 

I have the application up and running on AL2023 with NGINX

**Comment by gavinc-git** [comment]
> @gavinc-git You need to build the GUI first by running
> 
> ' prepare_assets.sh ' that depends on yarn. After you built that you just do go build.

Worked a treat thank you.

Had to convert from CRLF to LF
