### ISSUE TITLE
Client - is a server with default route (0.0.0.0/0)

### ISSUE THREAD

**Issue by mrAntonD** [ngoduykhanh/wireguard-ui#649]
In my case, one of my wireguard clients is a client-server through which traffic should be routed by default (0.0.0.0/0). It is impossible to implement such a configuration of this client through the wireguard-ui interface. And you have to edit the config with your hands every time.
I ask you to implement this in the wireguard-ui interface. Please :-)

see the example below:

/etc/wireguard/wg0.conf
[Interface]
Address = 10.20.30.1/24
ListenPort = 17968
PrivateKey = ...
MTU = 1450
PostUp = /opt/wireguard-ui/postup.sh
PreDown =
PostDown = /opt/wireguard-ui/postdown.sh
Table = auto

[Peer]
PublicKey = ...
PresharedKey = ...
AllowedIPs = 10.20.30.2/32, **0.0.0.0/0**
PersistentKeepalive = 15

**Comment by alex-arzner-pro** [comment]
I have exactly the same situation, and everything works if you simply add 0.0.0.0/0 in Extra Allowed IPs (MAIN-> Wireguard Clients-> your client)

**Comment by mrAntonD** [comment]
> I have exactly the same situation, and everything works if you simply add 0.0.0.0/0 in Extra Allowed IPs (MAIN-> Wireguard Clients-> your client)

I didn't understand what "Extra Allowed IPs" meant. Thanks!
