### ISSUE TITLE
How to change admin default password?

### ISSUE THREAD

**Issue by DillFrescott** [ngoduykhanh/wireguard-ui#72]
I can't seem to figure out how to change it...

**Comment by DillFrescott** [comment]
Nevermind i figured it out

**Comment by PrzemekSkw** [comment]
@DillFrescott How did You change it?
Regards.

**Comment by DillFrescott** [comment]
@PrzemekSkw To be honest I don't remember. I apologize.

**Comment by PrzemekSkw** [comment]
Hi, I find that on another issue. I change in '/db/server/users.json'.
Do You know it's possibile to use my old wireguard config and do I need to run './wireguard-ui' as root to make it work?
Regards.

**Comment by DillFrescott** [comment]
I don't know. Sorry
