### ISSUE TITLE
Change to sqlite or other relational database

### ISSUE THREAD

**Issue by Computroniks** [ngoduykhanh/wireguard-ui#75]
Currently a number of JSON files are used in order to save user data. Would it be worth moving to a relational database system such as sqlite?  This would have a few advantages over the current JSON files, particularly as there would now only be one file. There would be some issues though with the current situation in terms of changing the admin password. It would require some utility either in the web interface or terminal to change the password.

It could also be an idea to use enviroment variables or a .env file to pass some settings for a remote db server such as mariadb allowing the user to use their central database instead of local storage (perhaps this is a step too far for now).

I would be willing to work on this but just want to see other peoples opinions before I do.

**Comment by gosom** [comment]
Hi @Computroniks ,

this PR [ https://github.com/ngoduykhanh/wireguard-ui/pull/88 ] abstracts the storage. 
Once this is merged you can implement the interface for supporting sqlite, which I believe it's a good idea.

**Comment by Computroniks** [comment]
Great, I will get on with this in the next few weeks. Thanks for the info on the pr

**Comment by Computroniks** [comment]
Well, it's been a while. Sorry for not working on this. I got distracted with other projects and kind of forgot. I am going to start implementing this today and hopefully I should have it done by mid next week. At first I am only going to add support for MySQL/MariaDB with SQLite and PostgreSQL perhaps comming later. I think I will add the settings for the DB as commandline flags/environment variables. Again, sorry for neglecting this issue for so long.
