### ISSUE TITLE
Old wg0.conf will work?

### ISSUE THREAD

**Issue by PrzemekSkw** [ngoduykhanh/wireguard-ui#76]
Hello,
I have installed with './wireguard-ui'.sh' but I have my working wg0.conf file with peers configs in '/etc/WireGuard/' folder. 
Do I have to remove old file to make new clents configs works?
Regards.

**Comment by ngoduykhanh** [comment]
Unfortunately, we don't support importing the config from an existing config file. You have to make the new client list.
