### ISSUE TITLE
Only first AllowedIP in WG configuration file

### ISSUE THREAD

**Issue by daw87** [ngoduykhanh/wireguard-ui#77]
I started the wireguard-ui using the docker-compose file. Everything seemd to work fine until I added the first client. Since I have a more complex setup with different sub-sites connecting to the wireguard server I need to route several networks.
Thats why every client has at least two AllowedIP ranges, some more. I can enter them correctly in the ui and they are saved correctly in the json file but when I click "apply config" only the first allowed IP is transferred to the WG config file.

**Comment by gosom** [comment]
I cannot reproduce the issue you describe

**Comment by daw87** [comment]
OK, let me show you. I pulled the code via docker-compose:
`version: '3'

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    ports:
      - 10.10.10.10:5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard`

Here is a screenshot of some of my current clients:
![grafik](https://user-images.githubusercontent.com/17311545/134821703-583de209-8c0d-4f15-9020-27d4f19df674.png)

And here is one of the corresponding config files from the "db" folder:
`{
        "id": "c43cdip0ca2uqohbfii0",
        "private_key": "xxxxxxxxxxxx",
        "public_key": "xxxxxxxxxx",
        "preshared_key": "xxxxxxxxxx",
        "name": "xxxxxxxxxxxxx",
        "email": "xxxxxxxxxxxxxxxxxxxx",
        "allocated_ips": [
                "10.x.x.x/32"
        ],
        "allowed_ips": [
                "10.x.x.x/32",
                "10.x.x.x/24"
        ],
        "enabled": true,
        "created_at": "2021-08-01T16:07:39.837534572Z",
        "updated_at": "2021-09-26T19:34:34.261997238Z"
}`

So until this point everything looks perfectly fine. Now, here is the part just generated wg-config file:
`# ID:           c43cdip0ca2uqohbfii0
# Name:         xxxxxxxxxxxxx
# Email:        xxxxxxxxxxxxxxxxxxxx
# Created at:   2021-08-01 16:07:39.837534572 +0000 UTC
# Update at:    2021-09-26 19:34:34.261997238 +0000 UTC
[Peer]
PublicKey = xxxxxxxxxx
PresharedKey = xxxxxxxxxx
AllowedIPs = 10.x.x.x/32`

So in this example there is one IP missing. There are other examples with more AllowedIPs and there is not one shown in the config. Any ideas?

**Comment by daw87** [comment]
I just started testing a little bit and I think I have to correct my observation: It's not just the first IP from AllowedIPs, it's really just the allocatedIP (/32). I went through the source and found this in wireguard-ui/templates/wg.conf:
`[Peer]`
`PublicKey = {{ .Client.PublicKey }}`
`PresharedKey = {{ .Client.PresharedKey }}`
`AllowedIPs = {{$first :=true}}{{range .Client.AllocatedIPs }}{{if $first}}{{$first = false}}{{else}},{{end}}{{.}}{{end}}`
`{{end}}{{end}}`
Shouldn't _.Client.AllocatedIPs_ be replaced by _.Client.AllocatedIPs__?

**Comment by ngoduykhanh** [comment]
Those allowed IP networks are written to the client config file, not the server config file that you looked at.

**Comment by e-bits** [comment]
Hi @ngoduykhanh,
I'm pretty new to Wireguard but I need to say I do not agree with your statement here:
> Those allowed IP networks are written to the client config file, not the server config file that you looked at.

I mean, yes they are written in client config but they need to go into Server config as well. According to the [Cryptokey Routing](https://www.wireguard.com/#cryptokey-routing) there is a clear sentence about that behavior.

> In the server configuration, when the network interface wants to send a packet to a peer (a client), it looks at that packet's destination IP and compares it to each peer's list of allowed IPs to see which peer to send it to. For example, if the network interface is asked to send a packet with a destination IP of 10.10.10.230, it will encrypt it using the public key of peer gN65BkIK..., and then send it to that peer's most recent Internet endpoint.

Please correct me if I'm wrong, I really like your project and try to help to pushing it further. 
Btw. I think this MR is also related to this issue:  #114 

Thanks for your work
e-bits

**Comment by ngoduykhanh** [comment]
@e-bits I know that. My statement was about the current design of the wireguard-ui.
To support more scenarios, we need to add more flexibility in wg config generation. #114 was one of PR to improve it.

**Comment by solova-alex** [comment]
I understand the solution has not been found? I also like your product, I edit the  script when the server config is applied
