### ISSUE TITLE
Upgrade to Latest Ver

### ISSUE THREAD

**Issue by Gamexland** [ngoduykhanh/wireguard-ui#85]
Hi,

I have 0.2.7 on my server , How can I upgrade to 0.3.0 without loosing my accounts and Data's ?
I am newbie and beginner so pls explain exactly what shall I do

**Comment by ngoduykhanh** [comment]
Hi,

It won't remove the old data. However, you can always make a backup before upgrading. There is a `db` directory where we store all config information.
Just download the new binary file and replace the old one. If you are using Docker image, just update the tag.
