### ISSUE TITLE
User management & Access control

### ISSUE THREAD

**Issue by ngoduykhanh** [ngoduykhanh/wireguard-ui#9]
It would be nice if we can have multiple users access. Each user has their own Wireguard client setup.

Only Admin can manage the Wireguard server config

**Comment by tituspijean** [comment]
I am currently integrating the UI into YunoHost (selfhosting orchestration based on Debian). Since YunoHost's SSO has its own login page, is it possible to disable your logging system altogether?

It seems that only putting `{}` in `db/server/users.json` allows for any input to be accepted, but maybe we can bypass the login page completely?

**Comment by ngoduykhanh** [comment]
@tituspijean I've added an option to disable authentication, you can try with `--disable-login` command-line argument.

**Comment by tituspijean** [comment]
Yes, I saw your new release. It works great, thanks!

I mimicked what you did to allow for other binding addresses too. See the related PR. ;)

**Comment by ngoduykhanh** [comment]
Yes, I saw it and added a few comments there. Can you check?

**Comment by tituspijean** [comment]
There is an issue though, after disabling authentication, with the now irrelevant user name on the homepage: "%!s()"

![Capture d’écran 2020-10-10 153113](https://user-images.githubusercontent.com/8769166/95656290-aa9f9e80-0b0d-11eb-888d-fcc1e3754c39.png)

**Comment by ngoduykhanh** [comment]
oops, I've just fixed it on the master branch.

**Comment by PrzemekSkw** [comment]
@ngoduykhanh Hi, I don't want to open new issue. Can You tell me how to change login and password. I run with binary file `./wireguard-ui`?
Regards.

**Comment by Anas-Sherif** [comment]
Also maybe if we get multiple users you can connect it to OCID and have each user connected to your SSO service.

**Comment by bitdruid** [comment]
> @tituspijean I've added an option to disable authentication, you can try with `--disable-login` command-line argument.

may i ask you if it is possible to disable the login on the docker container? keep the env empty?
