### ISSUE TITLE
changing password ?

### ISSUE THREAD

**Issue by istvanSA** [ngoduykhanh/wireguard-ui#93]
i've created :

version: "3"

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    environment:
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=testthis-unusual-password
    ports:
      - 5000:5000
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard

but after a docker-compose up the username and password that are accepter are admin/admin ?

**Comment by ngoduykhanh** [comment]
The docker hub image is updated now.
