### ISSUE TITLE
How to add a sub network when creating a client?

### ISSUE THREAD

**Issue by zGansalloz** [ngoduykhanh/wireguard-ui#96]
How to add a sub network when creating a client?
IP Allocation: 10.252.1.2/32, 192.168.0.0/24

10.252.1.2/32 - VPN network.
192.168.0.0/24 - Local network.
But I get the following error.
IP 192.168.0.0 does not belong to any network addresses of WireGuard server

Tell me how to be?

**Comment by N4v41** [comment]
in this case you want to enable the client to have multiple addresses or allow it to acess the internal network ?

**Comment by zGansalloz** [comment]
Yes,  acess the internal network.

**Comment by N4v41** [comment]
in this case you sould put the network in the allowed ips list, if i'm not wrong the ip allocation will work only in the the context of the wireguard interface, you need to foward and nat the traffic to another interface of the server for accessing internal resources on the network.

**Comment by zGansalloz** [comment]
I don’t understand you, the language barrier seems to be affecting. Or lack of my knowledge.

> in this case you sould put the network in the allowed ips list, if i'm not wrong the ip allocation will work only in the the context of the wireguard interface, you need to foward and nat the traffic to another interface of the server for accessing internal resources on the network.

**Comment by N4v41** [comment]
to enable the clients to acess the internal network you should just add post up and post down scripts to nat the traffic:
![image](https://user-images.githubusercontent.com/45365461/134174021-c19d45d8-f5a4-41c0-9588-3b4f6d4abde4.png)

i use this:
post up: iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
post down: iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

using these scripts i'm allowed to access the internal network with this configuration.
![image](https://user-images.githubusercontent.com/45365461/134174388-f4bcc643-51ff-4dbe-aeda-4a00f5bdde01.png)

**Comment by zGansalloz** [comment]
Many thanks. But the problem turned out to be in the routes.
