### ISSUE TITLE
Default password

### ISSUE THREAD

**Issue by NOXCIS** [ngoduykhanh/wireguard-ui#97]
The default password cannot be modified through the docker-compose file. The current environment variables serve no purpose and have stood to server no purpose for quite some time.

**Comment by paklids** [comment]
This most certainly works for me. Here is my docker-compose.yml and I'm using ngoduykhanh/wireguard-ui:latest (when checking `docker images --digests` you should see a SHA256 start with 6f9a448d59a8)

  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=${wgui_username}
      - WGUI_PASSWORD=${wgui_password}
    logging:
      driver: json-file
      options:
        max-size: 100m

**Comment by NOXCIS** [comment]
I resolved the issue as I did realize we set a password before building.
