### ISSUE TITLE
Feature request: Making e-mail, MTU and keepalive optional

### ISSUE THREAD

**Issue by kirichkov** [ngoduykhanh/wireguard-ui#98]
First of all thanks for the great work, you've done! Makes managing wireguard tunnels a breeze!

I'd be glad to see on the client side e-mail to be optional. Currently it is possible to achieve this by directly editing the json files, but it'd be better if one could simply omit the e-mail field for simple and fast addition of clients.

On the service side, if you don't specify KeepAlive it is set to 0, rather than being completely omitted.
The same goes for MTU - the WireGuard Android app even recommends leaving it to auto.

**Comment by ngoduykhanh** [comment]
Client email input is optional now. #109 
I will check the other two

**Comment by kirichkov** [comment]
Thank you!
